const CITY={rome:{title:'로마',latin:'Roma',intro:'10월 3일 19:15 도착 · Memphis 1박 예약 완료(조식 포함). 4일 FR8317 15:57 → 바리 20:20, Standard Base €61 예약·발권 완료.',center:[41.8927,12.4817],zoom:13,days:[['10.3 토','19:15 FCO 도착 · 로마 1박'],['10.4 일','15:57 기차 → 바리 · 발권 완료']]},bari:{title:'바리',latin:'Bari',intro:'10/4 20:20 도착 → Moderno 21시 체크인 예상 · 1박 예약 완료. 5일 체크아웃·짐 회수 → Nicolaus 13시 목표, GEMINI 14시 참석 후보.',center:[41.1145,16.866],zoom:13,days:[['10.4 일','바리 도착 · Moderno 예약 완료'],['10.5 월','니콜라우스 확정 숙박 시작'],['10.6–8','ISMAR 학회 · 저녁 탐방'],['10.9 금','08:40 FR8306 · 귀국 발권 완료']]}};
const CATEGORY={food:'식당',drink:'바·클럽',stay:'숙소',coffee:'카페·아침',shop:'쇼핑',transit:'교통',area:'동네',sight:'관광·산책'};
const PLACES=[
 {id:'fco',city:'rome',name:'피우미치노 공항 (FCO)',category:'transit',area:'피우미치노',lat:41.8153911,lng:12.2264848,desc:'10월 3일 19:15 도착. 테르미니역까지 레오나르도 익스프레스 이용.',day:'10.3',status:'확정',url:'https://www.trenitalia.com/en/connections/leonardo-express.html'},
 {id:'termini',city:'rome',name:'로마 테르미니역',category:'transit',area:'에스퀼리노',lat:41.9005815,lng:12.5025272,desc:"10월 4일 FR8317 Roma Termini 15:57 → Bari Centrale 20:20, 직통 4시간 23분. Standard / Base €61 예약·발권 완료. Base 출발 전 변경 가능(차액), 출발 전 취소 20% 공제. 큰 짐 직접 운반·적재, 통로 막지 않기; 좌석 예약이 짐 공간 보장은 아님.",day:'10.4',status:'예약·발권 완료',url:'https://www.trenitalia.com/en.html'},
 {id:'mercato-centrale',city:'rome',name:'Mercato Centrale Roma',category:'food',area:'테르미니역',lat:41.8986062,lng:12.5037971,desc:'3일 늦게 도착했을 때 편한 식사 대안. 매일 23:30까지 운영.',day:'10.3',status:'후보',url:'https://www.mercatocentrale.com/rome/info/'},
 {id:'monti',city:'rome',name:'몬티 · 로마 숙소 후보 구역',category:'area',area:'몬티',lat:41.8948271,lng:12.4928952,desc:'식당과 와인바가 많고 테르미니역 접근이 편한 숙박 후보 동네. 야경은 몬티 외 다른 구역도 검토.',note:'숙소는 Memphis 예약 완료. 몬티와 기존 숙소들은 대안으로 보관합니다.',day:'',status:'후보',url:'https://www.turismoroma.it/en/page/rione-i-monti'},
 {id:'raffaello',city:'rome',name:'Hotel Raffaello',category:'stay',area:'몬티 · 비아 우르바나',lat:41.897779,lng:12.495549,desc:'역 접근과 동네 분위기의 균형. 테르미니역 도보 약 5분(호텔 안내). 객실은 안쪽을 요청하면 좋음.',day:'10.3',status:'후보',url:'https://www.hotelraffaello.it/en/'},
 {id:'domus-harmonia',city:'rome',name:'Domus Harmonia Hotel',category:'stay',area:'몬티 · 비아 파니페르나',lat:41.897114,lng:12.494253,desc:'작은 2성급 숙소. 테르미니역 도보 약 10분, 카보우르역 약 3분(호텔 안내).',day:'10.3',status:'후보',url:'https://www.domusharmoniahotel.it/en/home-en/'},
 {id:'lancelot',city:'rome',name:'Hotel Lancelot',category:'stay',area:'첼리오',lat:41.888261,lng:12.497136,desc:'주거지 분위기의 조용한 첼리오. 트라토리아·와인바가 가까움. 테르미니역에서는 택시 또는 지하철 이동.',day:'10.3',status:'후보',url:'https://www.lancelothotel.com/location/'},
 {id:'testaccio',city:'rome',name:'테스타초',category:'area',area:'테스타초',lat:41.8795062,lng:12.474483,desc:'로마 전통 음식과 트라토리아가 많은 동네. 4일 점심 산책 구역.',day:'10.4',status:'후보',url:'https://www.turismoroma.it/en/quartieri/trastevere-testaccio'},
 {id:'felice',city:'rome',name:'Felice a Testaccio',category:'food',area:'테스타초',lat:41.8785014,lng:12.4774658,desc:'Via Mastro Giorgio 29. 10월 4일 점심 후보, 미예약. 테스타초에서 호텔 짐 회수 후 Termini까지 이동 여유를 별도로 계산해야 함.',day:'10.4',status:'예약 전',url:'https://feliceatestaccio.com/'},
 {id:'trastevere',city:'rome',name:'트라스테베레',category:'area',area:'트라스테베레',lat:41.8911586,lng:12.4668459,desc:'골목 산책, 와인바와 밤 분위기를 즐기기 좋은 동네.',day:'10.4',status:'후보',url:'https://www.turismoroma.it/en/quartieri/trastevere-testaccio'},
 {id:'trapizzino',city:'rome',name:'Trapizzino Trilussa',category:'drink',area:'트라스테베레',lat:41.8914619,lng:12.4699126,desc:'라치오 와인과 트라피치노·수플리를 함께 즐기는 곳.',day:'10.4',status:'후보',url:'https://www.trapizzino.it/en/trapizzino/trapizzino-roma-trastevere/'},
 {id:'freni',city:'rome',name:'Freni e Frizioni',category:'drink',area:'트라스테베레',lat:41.8912836,lng:12.4706695,desc:'광장 옆에서 아페리티보와 칵테일을 즐기는 바.',day:'10.4',status:'후보',url:'https://www.freniefrizioni.com/'},
 {id:'roscioli',city:'rome',name:'Salumeria Roscioli',category:'food',area:'캄포 데 피오리',lat:41.89422,lng:12.4742602,desc:'Via dei Giubbonari 21. 10월 4일 점심 후보이나 10/1 조회 시 1인 온라인 예약 불가(날짜 비활성). 취소자리·전화예약 가능성 미확인. 실제 예약 없음.',day:'10.4',status:'예약 전',url:'https://roscioli.com/en-GB/salumeria'},
 {id:'campo',city:'rome',name:'캄포 데 피오리',category:'area',area:'중심가',lat:41.8955774,lng:12.4721586,desc:'Roscioli 주변 동네. 저녁 산책과 아페리티보 구역.',day:'10.4',status:'후보',url:'https://www.turismoroma.it/en/node/1514'},
 {id:'drinkkong',city:'rome',name:'Drink Kong',category:'drink',area:'몬티',lat:41.8951436,lng:12.4978655,desc:'칵테일이 목적일 때. 매일 18:30–02:00 영업.',day:'',status:'후보',url:'https://www.drinkkong.com/'},
 {id:'sanctuary',city:'rome',name:'The Sanctuary',category:'drink',area:'몬티',lat:41.8928103,lng:12.4982915,desc:'DJ와 칵테일을 즐기는 공간. 일요일은 02:00까지 운영.',day:'10.4',status:'후보',url:'https://www.thesanctuaryecoretreat.com/roma/roma-pool-area/'},
 {id:'circolo',city:'rome',name:'Circolo degli Illuminati',category:'drink',area:'오스티엔세',lat:41.8645846,lng:12.4810013,desc:'클럽. 10월 3일 MINÛ 행사, 일요일에도 23:00부터 클럽 운영.',day:'',status:'후보',url:'https://www.circolodegliilluminati.it/'},
 {id:'bari-station',city:'bari',name:'바리 첸트랄레역',category:'transit',area:'무라트',lat:41.1176721,lng:16.8700657,desc:'10월 4일 FR8317 20:20 도착 · Standard / Base €61 예약·발권 완료. 4–5일 Hotel Moderno 예약 완료. 20:20 역 도착 → Moderno 21시 체크인 예상 → 저녁.',day:'10.4',status:'예약·발권 완료',url:'https://www.ieeeismar.net/2026/getting-around-bari/'},
 {id:'nicolaus',city:'bari',name:'The Nicolaus Hotel',category:'stay',area:'포조프랑코',lat:41.0991824,lng:16.8548241,desc:'10월 5–9일 숙박 확정 · ISMAR 학회 장소. 10/4–5 Hotel Moderno 예약 완료. 10/5 Moderno 체크아웃·짐 회수 후 Nicolaus로 이동. 10/5 GEMINI 워크숍 참석 예정 후보: 현지 14:00–17:45, Sezione 2(15:30–16:15 휴식). 권장 동선: 오전 바리 시내 카페·산책 → 체크아웃·점심·짐 회수 → 택시로 12:45–13시 Nicolaus 도착 → 짐 보관 요청·배지 수령 → 13:45 행사장 → 14시 워크숍 → 종료 후 객실 체크인. 일반 체크인 15시부터로 조기 입실 보장 없음. 체크인 전 짐 보관과 월요일 등록데스크 운영시간 미확인.',day:'10.5',status:'예약 완료',url:'https://www.ieeeismar.net/2026/overview/'},
 {id:'gola',city:'bari',name:'Gola Caffè Bistrot',category:'food',area:'포조프랑코',lat:41.0974733,lng:16.8551844,desc:'호텔 근처 식당. 스파게티 알라사시나 후보.',day:'10.5',status:'후보',url:'https://www.ieeeismar.net/2026/venue/'},
 {id:'giotto',city:'bari',name:'Giotto Pizzeria',category:'food',area:'포조프랑코',lat:41.1036854,lng:16.853935,desc:'호텔 근처 피자 대안. 월–목 저녁 19:45–23:30 운영.',day:'',status:'후보',url:'https://www.giottopizzeria.it/'},
 {id:'bari-vecchia',city:'bari',name:'바리 베키아',category:'area',area:'구시가지',lat:41.1296759,lng:16.8695799,desc:'푸글리아 음식과 밤 산책을 즐기는 바리의 구시가지.',day:'',status:'후보',url:'https://www.italia.it/en/puglia/bari/bari-vecchia'},
 {id:'mercantile',city:'bari',name:'피아차 메르칸틸레',category:'sight',area:'바리 베키아',lat:41.1280581,lng:16.8717745,desc:'구시가지의 바와 식당이 모이는 광장.',day:'',status:'후보',url:'https://tour.puglia.it/en/things-to-see/bari/entertainment-venues/piazza-mercantile'},
 {id:'mercantile-nove',city:'bari',name:'Mercantile Nove',category:'drink',area:'바리 베키아',lat:41.127983,lng:16.8715617,desc:'피아차 메르칸틸레의 와인·칵테일 바.',day:'',status:'후보',url:'https://www.mercantilenove.it/'},
 {id:'mastrociccio',city:'bari',name:'Mastro Ciccio',category:'food',area:'바리 베키아 입구',lat:41.1262695,lng:16.8711072,desc:'푸글리아식 파니니·판제로티 등으로 가볍게 한 끼.',day:'',status:'후보',url:'https://www.mastrociccio.it/'},
 {id:'ferrarese',city:'bari',name:'피아차 델 페라레세',category:'sight',area:'바리 베키아',lat:41.1269251,lng:16.8719518,desc:'구시가지와 바닷가 사이, 저녁 산책 시작점.',day:'',status:'후보',url:'https://www.italia.it/en/puglia/bari/piazza-del-ferrarese'},
 {id:'lungomare',city:'bari',name:'룽고마레 나차리오 사우로',category:'sight',area:'해안',lat:41.1209717,lng:16.8837471,desc:'저녁 식사 전후 바다를 따라 걷기 좋은 구간.',day:'',status:'후보',url:'https://www.italia.it/en/puglia/bari/bari-vecchia'}
];
PLACES.push(...ROME_CANDIDATES,...BARI_CANDIDATES,
{"id":"emma","city":"rome","name":"Emma · 10/4 점심 추천","category":"food","area":"Via del Monte della Farina 28/29","address":"Emma, Via del Monte della Farina 28/29, Roma","lat":41.8947606,"lng":12.4752094,"day":"10.4","status":"후보","desc":"12:30 점심 추천 · 미예약, 자리 가능 여부 미확인. 로마식 얇고 바삭한 피자. 공식 통상 점심 매일 12:30–15:30, 10/4 공휴일 운영은 재확인. 공식 영문 메뉴 표시값: Margherita €10 / bufala Margherita €13 / supplì €4 / carbonara €17. 추천 bufala + supplì, 음료·추가 비용 별도. 13:40까지 출발 → Memphis 도보 약 30분 추정, 14:15 호텔 도착 목표. 실제 이동·대기 시간을 확인하고 식사를 길게 끌지 않기.","url":"https://emmapizzeria.com/","mapSource":"https://www.openstreetmap.org/node/4802113121","bookingSource":"https://emmapizzeria.com/wp-content/uploads/2025/12/MENU_WEB-INGLESE_Aprile2025.pdf"},
{"id":"colonna","city":"rome","name":"Piazza Colonna · 판테온 가는 길","category":"sight","area":"Piazza Colonna","address":"Piazza Colonna, Roma","lat":41.9008335,"lng":12.4799625,"day":"10.4","status":"후보","desc":"Memphis 또는 Rinascente에서 판테온으로 가는 길의 광장 경유. 핀은 OSM 광장 대표점. 10/4는 Spagna를 반복하지 않고 Colonna → Pantheon 외관 → Navona → Emma로 연결.","url":"https://www.openstreetmap.org/way/724033212","mapSource":"https://www.openstreetmap.org/way/724033212"},
{"id":"return-fr8306","city":"bari","name":"10/9 Frecciarossa 8306 · 발권 완료","category":"transit","area":"Bari Centrale → Roma Termini","lat":41.1176721,"lng":16.8700657,"day":"10.9","status":"예약·발권 완료","desc":"2026/10/9 Frecciarossa 8306 Bari Centrale 08:40 → Roma Termini 13:15 · Standard / Economy €46.90 · 예약·발권 완료. 이탈리아 현지 Europe/Rome, CEST(UTC+2). 07:50 Nicolaus 출발·08:10 Bari Centrale 도착은 계획용 목표이며 실제 교통·체크아웃에 맞춰 조정.","url":"https://www.trenitalia.com/en.html"},
{"id":"return-leonardo","city":"rome","name":"10/9 Leonardo Express · 추천·미구매","category":"transit","area":"Roma Termini → FCO","lat":41.9005815,"lng":12.5025272,"day":"10.9","status":"선택 · 미발권","desc":"10/9 판매표 확인 추천안: Roma Termini 16:35 → Fiumicino Aeroporto 17:07 · €14, 아직 미구매. 이탈리아 현지 Europe/Rome, CEST(UTC+2). 13:15 도착 후 점심·카페·휴식, 16시 전후 역 복귀 목표로 짐과 승강장 이동 여유 확보. 10/6–23 일부 Leonardo Express 시간 변경·취소 및 대체버스 공지: 출발 전 실제 운행·판매시간표 재확인. 16:35편의 정상 운행을 보장하는 의미가 아님.","url":"https://www.trenitalia.com/it/informazioni/lavori-programmati/20261006-linee-roma-termini-fiumicino-aeroporto-roma-velletri-roma-pisa.html"},
{"id":"return-flight","city":"rome","name":"귀국 항공 · FCO → ICN","category":"transit","area":"FCO · 인천 도착은 다음 날","lat":41.8153911,"lng":12.2264848,"day":"10.9","status":"확정","desc":"FCO 출발 2026/10/9 21:15 · 이탈리아 현지 Europe/Rome, CEST(UTC+2) → ICN 도착 2026/10/10 16:10 · 한국 현지 Asia/Seoul, KST(UTC+9). 추천 공항철도 17:07 공항역 도착 후 터미널 이동·체크인·짐 위탁·보안검색·출국 수속 여유 확보. 역 도착부터 항공 출발까지 약 4시간 8분, 수속·터미널 이동 시간 포함. 실제 항공사 카운터 오픈 시간은 미확인.","url":"https://www.adr.it/web/aeroporti-di-roma-en/pax-fco-before-travelling"});
Object.assign(PLACES.find(p=>p.id==='roscioli'),{address:'Salumeria Roscioli, Via dei Giubbonari 21, Roma',url:'https://salumeriaroscioli.com/en/pages/prenota'});
Object.assign(PLACES.find(p=>p.id==='felice'),{address:'Felice a Testaccio, Via Mastro Giorgio 29, Roma'});
Object.assign(PLACES.find(p=>p.id==='termini'),{address:'Roma Termini, Piazza dei Cinquecento, Roma',url:'https://www.trenitalia.com/it/informazioni/la-guida-del-viaggiatore/offerte-commerciali.html',bookingSource:'https://www.lefrecce.it/Channels.Website.WEB/'});
const STORAGE_KEY='italia-trip-map-v1';
Object.assign(PLACES.find(p=>p.id==='trevi'),{status:'방문 완료',day:'10.3'});
Object.assign(PLACES.find(p=>p.id==='spagna'),{status:'방문 완료',day:'10.3',desc:'10/3 방문 완료. 10/4 현재 동선에서는 반복하지 않고 Colonna·Pantheon·Navona로 이동.'});
Object.assign(PLACES.find(p=>p.id==='pantheon'),{day:'10.4',desc:'10/4 Pantheon 외관·Piazza della Rotonda 산책이 기본. 첫 일요일 무료 입장은 현장 티켓·줄이 필요할 수 있고 일요일 10:30 미사로 방문 중단 가능. 짧은 줄과 점심까지 시간 여유가 있을 때만 내부 입장. 이후 Navona → 12:30 Emma.',url:'https://cultura.gov.it/luogo/pantheon'});
Object.assign(PLACES.find(p=>p.id==='navona'),{day:'10.4',desc:'10/4 Pantheon 외관 뒤 광장 산책 → 12:30 Emma 점심으로 연결. 도보시간은 추정이며 식당 도착 시간을 우선.'});
const VALID_DAYS=['','10.3','10.4','10.5','10.6','10.7','10.8','10.9'];
const VALID_STATUS=['예약·발권 완료','선택 · 미발권','후보','예약 전','예약 완료','방문 완료','확정','이동 예정'];
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
function loadSaved(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return data&&typeof data==='object'?data:{}}catch{return {}}}
function cleanCustomPlaces(items){return items.filter(p=>p&&typeof p.id==='string'&&p.id.startsWith('mine-')&&typeof p.name==='string'&&['rome','bari'].includes(p.city)&&CATEGORY[p.category]&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180).map(p=>({id:p.id.slice(0,80),city:p.city,name:p.name.slice(0,80),category:p.category,lat:p.lat,lng:p.lng,area:'나의 장소',desc:'내가 추가한 장소',note:String(p.note||'').slice(0,700),status:VALID_STATUS.includes(p.status)?p.status:'후보',day:VALID_DAYS.includes(p.day)?p.day:''}))}
let saved=loadSaved();
let customPlaces=Array.isArray(saved.customPlaces)?cleanCustomPlaces(saved.customPlaces):[];
let overrides=saved.overrides&&typeof saved.overrides==='object'?saved.overrides:{};
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify({customPlaces,overrides}))}
function allPlaces(){return [...PLACES.map(p=>({...p,...(overrides[p.id]||{}),isCustom:false})),...customPlaces.map(p=>({...p,isCustom:true}))]}
function findPlace(id){return allPlaces().find(p=>p.id===id)}
let city='rome',category='all',dayFilter='all',selectedId=null,editingId=null,editPoint=null,picking=false,toastTimer;
const map=L.map('map',{zoomControl:false,scrollWheelZoom:true}).setView(CITY.rome.center,CITY.rome.zoom);
L.control.zoom({position:'topright'}).addTo(map);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
const markers=L.layerGroup().addTo(map), routeLayer=L.layerGroup().addTo(map);
let pendingMarker=null;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3600)}
function visiblePlaces(){const q=$('#searchInput').value.trim().toLocaleLowerCase();return allPlaces().filter(p=>p.city===city&&(category==='all'||p.category===category)&&(dayFilter==='all'||p.day===dayFilter)&&(p.name+' '+p.area+' '+p.desc+' '+(p.note||'')).toLocaleLowerCase().includes(q))}
function iconFor(p){return p.category==='food'?'🍽':p.category==='coffee'?'☕':p.category==='shop'?'▣':p.category==='drink'?'◉':p.category==='stay'?'⌂':p.category==='transit'?'↗':'◇'}
function daysForCity(){return city==='rome'?[['10.3','3 토','19:15 도착 · 1박'],['10.4','4 일','15:57 바리 · 발권 완료'],['10.9','9 금','13:15 로마 · 21:15 FCO 귀국']]:[['10.4','4 일','Moderno 예약 완료'],['10.5','5 월','확정 숙박 시작'],['10.6','6 화','학회'],['10.7','7 수','학회'],['10.8','8 목','학회'],['10.9','9 금','08:40 FR8306 · 발권 완료']]}
function render(){
 const c=CITY[city];$('#cityTitle').innerHTML=`${c.title} <em>${c.latin}</em>`;$('#cityIntro').textContent=c.intro;$('#mapCityLabel').textContent=c.latin.toUpperCase();
 const days=daysForCity();$('#planStrip').innerHTML=`<button class="plan-card ${dayFilter==='all'?'active':''}" data-day="all" type="button"><b>전체 일정</b><span>모든 장소 보기</span></button>`+days.map(d=>`<button class="plan-card ${dayFilter===d[0]?'active':''}" data-day="${d[0]}" type="button"><b>10월 ${d[1]}</b><span>${d[2]}</span></button>`).join('');
 $$('.city-switch button').forEach(b=>{const yes=b.dataset.city===city;b.classList.toggle('active',yes);b.setAttribute('aria-selected',String(yes))});
 const cats=['all',...Object.keys(CATEGORY)];$('#categoryFilters').innerHTML=cats.map(k=>`<button type="button" data-category="${k}" class="${category===k?'active':''}">${k==='all'?'전체':CATEGORY[k]}</button>`).join('');
 const ps=visiblePlaces();$('#placeCount').textContent=ps.length;
 const card=p=>`<button type="button" class="place-card ${['memphis','bari-moderno'].includes(p.id)?'booked-card ':''}${selectedId===p.id?'active':''}" data-id="${escapeHTML(p.id)}" data-category="${escapeHTML(p.category)}"><span class="place-icon">${iconFor(p)}</span><span class="place-copy"><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(p.area)} · ${CATEGORY[p.category]}${p.day?' · '+p.day:''}</small><span class="status">${escapeHTML(p.status)}</span>${p.note?'<small class="card-note">'+escapeHTML(p.note)+'</small>':''}</span></button>`;
 const alternatives=ps.filter(p=>!p.isCustom&&((p.city==='rome'&&p.category==='stay'&&p.id!=='memphis')||(p.city==='bari'&&['bari-victor','bari-boston'].includes(p.id))));
 const main=ps.filter(p=>!alternatives.includes(p)).sort((a,b)=>(['memphis','bari-moderno'].includes(a.id)?-1:['memphis','bari-moderno'].includes(b.id)?1:0));
 $('#placeList').innerHTML=ps.length?main.map(card).join('')+(alternatives.length?'<details class="hotel-alternatives"><summary>대안 숙소 · '+alternatives.length+'곳 (미예약)</summary><p>이전 비교 후보입니다. '+(city==='rome'?'Memphis':'Hotel Moderno')+' 예약 완료; 아래 요금은 과거 조회값입니다.</p>'+alternatives.map(card).join('')+'</details>':''):'<div class="empty-state">해당하는 장소가 없습니다. 검색어나 필터를 바꿔보세요.</div>';
 markers.clearLayers();ps.forEach(p=>{const icon=L.divIcon({className:'',html:`<div class="map-pin ${p.category} ${selectedId===p.id?'selected':''}"></div>`,iconSize:[24,24],iconAnchor:[12,12]});L.marker([p.lat,p.lng],{icon,title:p.name}).addTo(markers).on('click',()=>{if(!picking)selectPlace(p.id)})});
 routeLayer.clearLayers();
}
function showDetail(id){const p=findPlace(id);if(!p)return;selectedId=id;render();map.flyTo([p.lat,p.lng],Math.max(map.getZoom(),15),{duration:.55});const source=p.url&&/^https?:\/\//i.test(p.url)?`<a href="${escapeHTML(p.url)}" target="_blank" rel="noopener">장소 정보 ↗</a>`:'';$('#dialogContent').innerHTML=`<div class="dialog-category">${CATEGORY[p.category]} / ${escapeHTML(p.area)}</div><h2>${escapeHTML(p.name)}</h2><p class="dialog-meta">${escapeHTML(p.status)}${p.day?' · 10월 '+escapeHTML(p.day.split('.')[1])+'일':' · 날짜 미정'}</p><p class="dialog-desc">${escapeHTML(p.desc||'내가 추가한 장소입니다.')}</p>${p.note?'<p class="dialog-note"><strong>내 메모</strong><br>'+escapeHTML(p.note)+'</p>':''}<div class="dialog-actions"><button type="button" id="editSelected">일정·메모 수정</button>${source}${p.mapSource?'<a href="'+escapeHTML(p.mapSource)+'" target="_blank" rel="noopener">좌표 출처 ↗</a>':''}${p.bookingSource?'<a href="'+escapeHTML(p.bookingSource)+'" target="_blank" rel="noopener">요금·예약조건 ↗</a>':''}${p.officialMap?'<a href="'+escapeHTML(p.officialMap)+'" target="_blank" rel="noopener">공식 위치 ↗</a>':''}<a href="https://www.openstreetmap.org/?mlat=${p.lat}&mlon=${p.lng}#map=17/${p.lat}/${p.lng}" target="_blank" rel="noopener">큰 지도 ↗</a>${p.isCustom?'<button type="button" id="deleteSelected" class="danger-button">삭제</button>':''}</div>`;$('#placeDialog').showModal()}
function selectPlace(id){showDetail(id)}
function openEditor(id=null){
 const p=id?findPlace(id):null;editingId=id;editPoint=p?[p.lat,p.lng]:null;const form=$('#placeForm');form.reset();
 form.elements.name.value=p?.name||'';form.elements.city.value=p?.city||city;form.elements.category.value=p?.category||'food';form.elements.day.value=VALID_DAYS.includes(p?.day)?p.day:'';form.elements.status.value=VALID_STATUS.includes(p?.status)?p.status:'후보';form.elements.note.value=p?.note||'';
 const fixed=!!p&&!p.isCustom;for(const key of ['name','city','category'])form.elements[key].disabled=fixed;$('#pickLocation').hidden=fixed;
 $('#editTitle').textContent=p?'장소 계획 수정':'장소 추가';$('#editHelp').textContent=fixed?'날짜, 예약 상태와 개인 메모를 수정할 수 있습니다.':'지도에서 원하는 지점을 선택하고 장소를 저장하세요.';updateCoords();$('#editDialog').showModal();
}
function updateCoords(){$('#coordsLine').textContent=editPoint?`선택한 위치 · ${editPoint[0].toFixed(5)}, ${editPoint[1].toFixed(5)}`:'위치를 선택해 주세요'}
function endPicking(){picking=false;$('#map').classList.remove('picking');$('#mapHint').textContent='핀을 선택해 상세 정보를 보세요'}
$$('.city-switch button').forEach(b=>b.addEventListener('click',()=>{city=b.dataset.city;category='all';dayFilter='all';selectedId=null;$('#searchInput').value='';map.setView(CITY[city].center,CITY[city].zoom);render();setTimeout(()=>map.invalidateSize(),120)}));
$('#planStrip').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(!b)return;dayFilter=b.dataset.day;selectedId=null;render()});
$('#categoryFilters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;render()});
$('#placeList').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)selectPlace(b.dataset.id)});
$('#searchInput').addEventListener('input',render);
$('#resetFilters').addEventListener('click',()=>{category='all';dayFilter='all';$('#searchInput').value='';render()});
$('#addBtn').addEventListener('click',()=>openEditor());
$('#editClose').addEventListener('click',()=>{$('#editDialog').close();endPicking()});
$('#placeDialog').addEventListener('click',e=>{if(e.target===$('#placeDialog'))$('#placeDialog').close()});
$('#editDialog').addEventListener('click',e=>{if(e.target===$('#editDialog')){$('#editDialog').close();endPicking()}});
$('#dialogContent').addEventListener('click',e=>{if(e.target.id==='editSelected'){$('#placeDialog').close();openEditor(selectedId)}if(e.target.id==='deleteSelected'){const p=findPlace(selectedId);if(!p?.isCustom)return;if(confirm(`“${p.name}” 핀을 삭제할까요?`)){customPlaces=customPlaces.filter(x=>x.id!==p.id);persist();$('#placeDialog').close();selectedId=null;render();toast('장소를 삭제했습니다.')}}});
$('#pickLocation').addEventListener('click',()=>{$('#editDialog').close();picking=true;$('#map').classList.add('picking');$('#mapHint').textContent='지도에서 새 핀 위치를 클릭하세요';toast('지도에서 장소의 위치를 클릭하세요.')});
function pickMapLocation(e){if(!picking)return;editPoint=[e.latlng.lat,e.latlng.lng];endPicking();if(pendingMarker)map.removeLayer(pendingMarker);pendingMarker=L.circleMarker(editPoint,{radius:9,color:'#173542',fillColor:'#f2b455',fillOpacity:1,weight:3}).addTo(map);updateCoords();$('#editDialog').showModal()}
map.on('click',pickMapLocation);
$('#map').addEventListener('click',e=>{if(picking&&!e.target.closest('.leaflet-control')&&!map.dragging._draggable._moved)pickMapLocation({latlng:map.mouseEventToLatLng(e)})});
$('#placeForm').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const name=form.elements.name.value.trim(),newCity=form.elements.city.value,cat=form.elements.category.value,day=form.elements.day.value,status=form.elements.status.value,note=form.elements.note.value.trim();if(!name){form.elements.name.focus();return}if(!editPoint){toast('지도에서 위치를 선택해 주세요.');return}if(editingId){const original=findPlace(editingId);if(original?.isCustom){const index=customPlaces.findIndex(p=>p.id===editingId);if(index>=0)customPlaces[index]={...original,name,city:newCity,category:cat,day,status,note,lat:editPoint[0],lng:editPoint[1],area:'나의 장소'}}else{overrides[editingId]={day,status,note}}}else{customPlaces.push({id:'mine-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name,city:newCity,category:cat,day,status,note,lat:editPoint[0],lng:editPoint[1],area:'나의 장소',desc:'내가 추가한 장소'})}try{persist()}catch{toast('브라우저 저장 공간을 사용할 수 없습니다. 내보내기로 백업해 주세요.')}$('#editDialog').close();if(pendingMarker){map.removeLayer(pendingMarker);pendingMarker=null}city=newCity;category='all';dayFilter='all';$('#searchInput').value='';render();toast('장소 계획을 저장했습니다.')});
$('#exportBtn').addEventListener('click',()=>{const file=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),customPlaces,overrides},null,2)],{type:'application/json'});const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download='italy-trip-map-2026.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('계획 파일을 내려받았습니다.')});
$('#importBtn').addEventListener('click',()=>$('#importInput').click());
$('#importInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.customPlaces)||!data.overrides||typeof data.overrides!=='object')throw new Error('format');const validCustom=cleanCustomPlaces(data.customPlaces);const byId=new Map([...customPlaces,...validCustom].map(p=>[p.id,p]));customPlaces=[...byId.values()];const allowed=new Set(PLACES.map(p=>p.id));for(const [id,value] of Object.entries(data.overrides)){if(allowed.has(id)&&value&&typeof value==='object')overrides[id]={day:VALID_DAYS.includes(value.day)?value.day:'',status:VALID_STATUS.includes(value.status)?value.status:'후보',note:String(value.note||'').slice(0,700)}}persist();render();toast('백업 내용을 불러왔습니다.')}catch{toast('이 페이지에서 만든 백업 파일을 선택해 주세요.')}e.target.value=''});
render();
