const ROME_CANDIDATES=[
  {
    "id": "memphis",
    "city": "rome",
    "name": "Hotel Memphis · 예약 완료",
    "category": "stay",
    "area": "Via degli Avignonesi 36 · Trevi 인근",
    "address": "Hotel Memphis, Via degli Avignonesi 36, Roma",
    "lat": 41.9028111,
    "lng": 12.4865252,
    "desc": "10/3–4 1박 · 결제·예약 확인 완료. Single Room 13㎡ · 싱글 침대 · 전용 욕실 · 조식 포함. 총 €186.85 = Agoda 결제 €179.35 + 현장 납부 €7.50. 환불·변경 불가. 이번 예약 체크인 14:00–23:00 / 체크아웃 11:00. 23시 이후 지연 도착 시 호텔에 연락: +39 06 485849 · memphis@remarhotels.com. 공식 24시간 프런트 안내가 늦은 입실을 무조건 보장하지는 않습니다. 체크아웃 후 무료 짐 보관, 14시 전후 회수 계획(호텔에 회수시각 확인). 조식 07:00–10:00(호텔 안내).",
    "day": "10.3",
    "status": "예약 완료",
    "url": "https://www.hotelmemphisroma.com/servizi",
    "mapSource": "https://maps.app.goo.gl/ZPuGSxdoe5cLJcxX9"
  },
  {
    "id": "pace-helvezia",
    "city": "rome",
    "name": "Hotel Pace Helvezia · Venezia 인근",
    "category": "stay",
    "area": "Via IV Novembre 104",
    "address": "Hotel Pace Helvezia, Via IV Novembre 104, Roma",
    "lat": 41.8968885,
    "lng": 12.4850648,
    "mapSource": "https://www.openstreetmap.org/relation/2054943",
    "url": "https://www.leonardihotels.com/en/hotel-hotel-pace-helvezia-in-rome/services/",
    "bookingSource": "https://www.booking.com/hotel/it/pacehelveziarome.en-gb.html?checkin=2026-10-03&checkout=2026-10-04&group_adults=1&no_rooms=1&group_children=0&selected_currency=EUR",
    "desc": "10/3–4 1인 · Double 19m² · 전용 욕실 · 조식 포함, 미예약·미선택. 10/1 08:36–08:39 UTC Booking 조회: 조식 포함 표시총액 €310 환불 불가·선결제 / 별도 €327 조식 포함 유연운임은 10/2 전 무료취소 표시(정확한 마감·조건 최종 확인). €237 room-only는 조식 비교에서 제외. Booking 표시총액은 세금 포함 whole-euro 반올림으로 VAT·도시세 개별내역 미표시. Piazza Venezia 인근·옥상 전망, 공식 24시간 프런트와 짐 보관 안내. 체크인 14:00 / 체크아웃 11:00. 보관 비용·최종 회수시간 미명시. 결제 전 요금·최종 조건 확인.",
    "day": "10.3",
    "status": "후보"
  },
  {
    "id": "abruzzi",
    "city": "rome",
    "name": "Albergo Abruzzi · Pantheon 앞 / 별관 후보",
    "category": "stay",
    "area": "Piazza della Rotonda 69 · 본관 접수 기준",
    "address": "Albergo Abruzzi, Piazza della Rotonda 69, Roma",
    "lat": 41.8993617,
    "lng": 12.4771123,
    "mapSource": "https://www.openstreetmap.org/node/1920404978",
    "url": "https://www.hotelabruzzi.it/services.php",
    "bookingSource": "https://www.booking.com/hotel/it/albergo-abruzzi.en-gb.html?checkin=2026-10-03&checkout=2026-10-04&group_adults=1&no_rooms=1&group_children=0&selected_currency=EUR",
    "desc": "10/3–4 1인 · Executive Annex 21m² · 조식 포함, 미예약·미선택. 10/1 08:36–08:39 UTC Booking 조회: 표시총액 €364 현장결제·선결제 없음, 단 취소·변경·노쇼 전액 부과. 판테온뷰 객실은 별도 €413, 현재 별관 후보에는 판테온뷰 보장 없음. 세금 포함 whole-euro 반올림 표시총액이며 VAT·도시세 개별내역 미표시. 지도핀·길찾기는 본관 Piazza della Rotonda 69 기준, 별관 위치·실제 체크인 동선 확인 필요. 24시간 프런트·도착시각 사전 알림, 체크인 14:00 / 체크아웃 12:00. 근처 식당 조식 07:30–10:30. 짐 보관 있으나 비용·최종 회수시간 미확인. 결제 전 최종 조건 확인.",
    "day": "10.3",
    "status": "후보"
  },
  {
    "id": "montecarlo",
    "city": "rome",
    "name": "Hotel Montecarlo",
    "category": "stay",
    "area": "Via Palestro 17/A, Roma",
    "lat": 41.906867,
    "lng": 12.501753,
    "desc": "싱글 · 전용 욕실 · 조식 포함, 미예약. 10/1 08:10 UTC Expedia 결제 전 내역: 총 €226.01(객실 €198.64 + 세금 €19.87 + 도시세 €7.50), 예약 시 €218.51 / 현장 €7.50. 환불 불가. Booking 앞선 조회는 도시세 €6로 상이, 결제 최종 조건 재확인. 취소·변경·노쇼 전액 부과. 조식 07:15–10:30, 체크아웃 11:00(공식). 체크인 14:00–24:00, Expedia 시간외 체크인 불가 안내. 항공 지연 시 사전 호텔 확인. 짐 보관 비용·체크아웃 후 가능 여부·회수시간은 미확인.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.hotelmontecarlo.it/en/services-3-star-hotel-rome",
    "mapSource": "https://www.openstreetmap.org/node/4238747989",
    "address": "Via Palestro 17/A, Roma",
    "bookingSource": "https://www.expedia.it/Rome-Hotel-Hotel-Montecarlo.h21175132.Informazioni-Hotel?chkin=2026-10-03&chkout=2026-10-04&rm1=a1"
  },
  {
    "id": "basilica",
    "city": "rome",
    "name": "Basilica Hotel",
    "category": "stay",
    "area": "Via Cavour 85/A, Roma",
    "lat": 41.8976633,
    "lng": 12.4961297,
    "desc": "싱글 · 전용 욕실 · 조식뷔페 포함 선택지, 미예약. 10/1 08:10 UTC Expedia 결제 전 내역: 총 €278(객실·조식 €247.27 + 세금 €24.73 + 도시세 €6), 예약 시 €272 / 현장 €6. 환불 불가. 취소·변경·노쇼 전액 부과. 조식 07:30부터(공식). 체크아웃 공식 10:00 / OTA 11:00로 상이: 10:00 기준 계획, 확인 필요. 체크인 Expedia anytime / Booking 23:30 상한으로 상이, 항공 지연 시 확인 필요. 짐 보관 비용·체크아웃 후 가능 여부·회수시간은 미확인.",
    "day": "10.3",
    "status": "후보",
    "url": "https://basilicahotel.it/it/camere/",
    "mapSource": "https://www.openstreetmap.org/node/13414226509",
    "address": "Via Cavour 85/A, Roma",
    "bookingSource": "https://www.expedia.it/Rome-Hotel-Dnb-House-Hotel.h13111460.Informazioni-Hotel?chkin=2026-10-03&chkout=2026-10-04&rm1=a1"
  },
  {
    "id": "mons",
    "city": "rome",
    "name": "MONS · 늦은 저녁 후보",
    "category": "food",
    "area": "Via della Fossa 16, Roma",
    "lat": 41.8992565,
    "lng": 12.4704828,
    "desc": "미예약. 금·토 18:00–03:00, 주방 02:00까지(공식). Navona 인근 식사 후 중심가 또는 Tiber 코스 연결. 방문일 운영 재확인.",
    "day": "",
    "status": "후보",
    "url": "https://monsroma.com/en/contacts/",
    "mapSource": "https://www.openstreetmap.org/node/6299620285",
    "address": "Via della Fossa 16, Roma"
  },
  {
    "id": "cimarra",
    "city": "rome",
    "name": "Cimarra 4",
    "category": "food",
    "area": "Via Cimarra 4, Roma",
    "lat": 41.8961355,
    "lng": 12.4905412,
    "desc": "몬티 저녁 대안, 미예약. 화–일 17:30–23:30, 주방 18:00–22:45(공식).",
    "day": "",
    "status": "후보",
    "url": "https://cimarra4.it/",
    "mapSource": "https://www.openstreetmap.org/node/10043599018",
    "address": "Via Cimarra 4, Roma"
  },
  {
    "id": "suburra",
    "city": "rome",
    "name": "Suburra 1930",
    "category": "food",
    "area": "Piazza della Suburra 13/15",
    "address": "Piazza della Suburra 13/15, Roma",
    "lat": 41.8947283,
    "lng": 12.4928568,
    "desc": "몬티 식당·칵테일 후보. 미예약. 영업·주방 마감은 확인 필요.",
    "day": "10.3",
    "status": "후보",
    "url": "https://suburra1930.it/",
    "mapSource": "https://maps.app.goo.gl/y6qzPdXEbDiKo7UQ7"
  },
  {
    "id": "navona",
    "city": "rome",
    "name": "Piazza Navona",
    "category": "sight",
    "area": "Piazza Navona, Roma",
    "lat": 41.8989282,
    "lng": 12.4731178,
    "desc": "중심가 야경 1번. 외관·광장 산책 후보, 미확정.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/way/4247138",
    "mapSource": "https://www.openstreetmap.org/way/4247138",
    "address": "Piazza Navona, Roma"
  },
  {
    "id": "pantheon",
    "city": "rome",
    "name": "Pantheon · 외관",
    "category": "sight",
    "area": "Piazza della Rotonda, Roma",
    "lat": 41.898616,
    "lng": 12.4768334,
    "desc": "중심가 야경 2번. 야간 외관 산책이며 내부 입장 계획 아님.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/relation/3374342",
    "mapSource": "https://www.openstreetmap.org/relation/3374342",
    "address": "Piazza della Rotonda, Roma"
  },
  {
    "id": "trevi",
    "city": "rome",
    "name": "Fontana di Trevi",
    "category": "sight",
    "area": "Piazza di Trevi, Roma",
    "lat": 41.9009778,
    "lng": 12.4832848,
    "desc": "10/3 저녁 후 핵심 야경. 외부 광장에서는 무료로 볼 수 있고 22시 이후에도 외부 감상 가능. 내부 구역은 관광객 €2, 토·일 09:00–22:00 / 마지막 입장 21:00(공식). 이번 계획은 내부 입장 없이 외부 관람. 현장 통제에 따라 조정.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.fontanaditrevi.roma.it/",
    "mapSource": "https://www.openstreetmap.org/relation/13448560",
    "address": "Piazza di Trevi, Roma"
  },
  {
    "id": "castel",
    "city": "rome",
    "name": "Castel Sant’Angelo · 외관",
    "category": "sight",
    "area": "Lungotevere Castello, Roma",
    "lat": 41.9031178,
    "lng": 12.4663427,
    "desc": "Tiber 야경 시작. 성 내부 입장이 아닌 외관 산책 후보.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/way/8035487",
    "mapSource": "https://www.openstreetmap.org/way/8035487",
    "address": "Lungotevere Castello, Roma"
  },
  {
    "id": "conciliazione",
    "city": "rome",
    "name": "Via della Conciliazione",
    "category": "sight",
    "area": "Via della Conciliazione, Roma",
    "lat": 41.9022534,
    "lng": 12.4635967,
    "desc": "St Peter 방향 도보 접근 후보.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/way/1346766550",
    "mapSource": "https://www.openstreetmap.org/way/1346766550",
    "address": "Via della Conciliazione, Roma"
  },
  {
    "id": "stpeter",
    "city": "rome",
    "name": "St Peter · 광장 외관",
    "category": "sight",
    "area": "Piazza San Pietro, Vatican",
    "address": "Piazza San Pietro, Vatican",
    "lat": 41.9022351,
    "lng": 12.4573573,
    "desc": "Tiber 코스 종점. 성당 내부 입장이 아닌 광장·외관 후보. 야간 보안 통제는 현장 확인.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/relation/10044166",
    "mapSource": "https://www.openstreetmap.org/relation/10044166"
  },
  {
    "id": "santamaria",
    "city": "rome",
    "name": "Santa Maria in Trastevere · 외관",
    "category": "sight",
    "area": "Piazza di Santa Maria in Trastevere, Roma",
    "lat": 41.8894229,
    "lng": 12.469501,
    "desc": "Trastevere 골목 코스 시작. 내부 관람이 아닌 광장·외관 산책 후보.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/way/51368975",
    "mapSource": "https://www.openstreetmap.org/way/51368975",
    "address": "Piazza di Santa Maria in Trastevere, Roma"
  },
  {
    "id": "trilussa",
    "city": "rome",
    "name": "Piazza Trilussa",
    "category": "sight",
    "area": "Piazza Trilussa, Roma",
    "lat": 41.8918206,
    "lng": 12.4700408,
    "desc": "Trapizzino 주변 광장. Trastevere 야경 중간점.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/relation/13499483",
    "mapSource": "https://www.openstreetmap.org/relation/13499483",
    "address": "Piazza Trilussa, Roma"
  },
  {
    "id": "pontesisto",
    "city": "rome",
    "name": "Ponte Sisto",
    "category": "sight",
    "area": "Ponte Sisto, Roma",
    "lat": 41.8923415,
    "lng": 12.4707478,
    "desc": "Tiber 보행교. Trastevere 코스 종점 후보.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/relation/5676442",
    "mapSource": "https://www.openstreetmap.org/relation/5676442",
    "address": "Ponte Sisto, Roma"
  },
  {
    "id": "colosseum",
    "city": "rome",
    "name": "Colosseum · 외관",
    "category": "sight",
    "area": "Piazza del Colosseo, Roma",
    "lat": 41.8902572,
    "lng": 12.4923841,
    "desc": "고대 로마 야경 시작. 조명·공사 상황 미확인, 야간 내부 입장 아님.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/relation/1834818",
    "mapSource": "https://www.openstreetmap.org/relation/1834818",
    "address": "Piazza del Colosseo, Roma"
  },
  {
    "id": "fori",
    "city": "rome",
    "name": "Via dei Fori Imperiali",
    "category": "sight",
    "area": "Via dei Fori Imperiali, Roma",
    "lat": 41.894246,
    "lng": 12.4853983,
    "desc": "고대 로마 코스 중간점. 조명·공사·보행 통제 미확인.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/way/243722805",
    "mapSource": "https://www.openstreetmap.org/way/243722805",
    "address": "Via dei Fori Imperiali, Roma"
  },
  {
    "id": "campidoglio",
    "city": "rome",
    "name": "Campidoglio",
    "category": "sight",
    "area": "Piazza del Campidoglio, Roma",
    "lat": 41.8932482,
    "lng": 12.4829853,
    "desc": "고대 로마 코스 종점. 언덕·계단을 포함할 수 있어 실제 길찾기 확인.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.openstreetmap.org/way/23055100",
    "mapSource": "https://www.openstreetmap.org/way/23055100",
    "address": "Piazza del Campidoglio, Roma"
  },
  {
    "id": "pincio",
    "city": "rome",
    "name": "Pincio 공원 · 후순위",
    "category": "sight",
    "area": "Pincio, Roma",
    "address": "Pincio, Roma",
    "lat": 41.9111279,
    "lng": 12.4795547,
    "desc": "도착일 늦은 시각에는 후순위. 핀은 OSM 공원 대표점이며 특정 전망대 입구 아님. 오르막·야간 접근은 길찾기와 현장 확인.",
    "day": "",
    "status": "후보",
    "url": "https://www.openstreetmap.org/relation/14026944",
    "mapSource": "https://www.openstreetmap.org/relation/14026944"
  },
  {
    "id": "camillo",
    "city": "rome",
    "name": "Camillo a Piazza Navona",
    "category": "food",
    "area": "Piazza Navona 79–81",
    "address": "Camillo a Piazza Navona, Piazza Navona 79-81, Roma",
    "lat": 41.8993372,
    "lng": 12.4733783,
    "desc": "미예약. 10/1 조회: 10/3 22:00 1인 실내, 10/4 점심 12:30·12:45·13:00 온라인 선택 가능 · 식당 확인 필요(실제 예약 없음). 매일 주방 23:30까지. 테이블 유지 15분, 취소 최소 2시간 전. 양식 제출만으로 확정되지 않으며 식당 확인 필요. 보증 필요 시 최종조건 확인. 파스타 €19 / Cesanese 글라스 €9(조회값). 핀은 공식 주소 79–81 범위의 OSM 80번 주소 대표점으로, 정확한 출입구는 공식 지도 링크 확인.",
    "day": "10.3",
    "status": "후보",
    "url": "https://camillopiazzanavona.it/orari-apertura",
    "mapSource": "https://www.openstreetmap.org/node/12055152255",
    "officialMap": "https://www.google.com/maps?cid=4150720921106640566",
    "bookingSource": "https://camillopiazzanavona.it/book-a-table-en"
  },
  {
    "city": "rome",
    "category": "stay",
    "day": "10.3",
    "status": "후보",
    "id": "madison",
    "name": "Hotel Madison",
    "area": "Via Marsala 60 · Termini 북측",
    "address": "Hotel Madison, Via Marsala 60, Roma",
    "lat": 41.9018333,
    "lng": 12.5033887,
    "mapSource": "https://www.openstreetmap.org/node/9662296135",
    "url": "https://hotelmadisonrome.reserve-online.net/about",
    "bookingSource": "https://www.expedia.it/Rome-Hotel-Hotel-Madison.h891981.Informazioni-Hotel?chkin=2026-10-03&chkout=2026-10-04&rm1=a1",
    "desc": "10/3–4 1인 · 조식뷔페 포함 싱글 11m², 미예약. 10/1 08:23–08:31 UTC Expedia 조회: 총 €229.45(예약 시 €223.45 + 현장 도시세 €6), 환불 불가. 별도 유연운임 €283.30 현장결제: 10/1 23:59 로마시간까지 무료취소, 이후 100% 부과. 24시간 프런트, 체크인 15:00–23:30(늦은 도착은 확인), 체크아웃 11:00. 짐 보관 서비스는 있으나 체크아웃 후 가능 시간·비용·최종 회수시간 미공개. 요금·잔여 객실·최종 조건 변동 가능."
  },
  {
    "city": "rome",
    "category": "stay",
    "day": "10.3",
    "status": "후보",
    "id": "virgilio",
    "name": "Hotel Virgilio",
    "area": "Via Palermo 30 · 중심가",
    "address": "Hotel Virgilio, Via Palermo 30, Roma",
    "lat": 41.8989876,
    "lng": 12.4920724,
    "mapSource": "https://www.openstreetmap.org/node/5438662783",
    "url": "https://www.hotelvirgilio.it/it/servizi",
    "bookingSource": "https://www.expedia.it/Rome-Hotel-Hotel-Virgilio.h793895.Informazioni-Hotel?chkin=2026-10-03&chkout=2026-10-04&rm1=a1",
    "desc": "10/3–4 1인 · 조식 포함 Classic double/twin 14m², 미예약. 10/1 08:23–08:31 UTC Expedia 조회: 총 €312.13(예약 시 €306.13 + 현장 도시세 €6), 선결제·환불 불가·변경 불가 partner offer. 24시간 프런트, 체크인 14:00–24:00, 체크아웃 12:00. 엘리베이터·짐 보관 목록 있음, 체크아웃 후 보관 시간·비용·회수시간 미확인. 요금·최종 조건 재확인."
  },
  {
    "city": "rome",
    "category": "stay",
    "day": "10.3",
    "status": "후보",
    "id": "rome-times",
    "name": "Rome Times Hotel · 접수 42 / 별관 58",
    "area": "Via Milano 42 · 접수 기준 핀",
    "address": "Rome Times Hotel, Via Milano 42, Roma",
    "lat": 41.8985684,
    "lng": 12.4904965,
    "mapSource": "https://www.openstreetmap.org/node/10926033345",
    "url": "https://www.rometimeshotel.com/en/",
    "bookingSource": "https://www.expedia.it/Rome-Hotel-Rome-Times-Hotel.h6024030.Informazioni-Hotel?chkin=2026-10-03&chkout=2026-10-04&rm1=a1",
    "desc": "10/3–4 1인 · Classic Annex 17m², 미예약. 10/1 08:23–08:31 UTC Expedia 조회: room-only 총 €325.46(예약 시 €317.96 + 현장 도시세 €7.50), 환불 불가. 조식 약 €15 추가 시 예상 €340.46이며 조식 포함 결제 견적이 아님. 접수·조식은 Via Milano 42 본관, 객실 별관은 58번(호텔 안내 50m 거리). 핀·코스 길찾기는 접수 42 기준. 24시간 안내·짐 보관, 체크아웃 11:00. 짐 회수 위치·시간·비용과 최종 조식 금액 확인 필요."
  },
  {
    "city": "rome",
    "category": "stay",
    "day": "10.3",
    "status": "후보",
    "id": "exe-domus",
    "name": "Exe Domus Aurea · 짐 접근성 확인 필요",
    "area": "Via Volturno 34 · 후순위",
    "address": "Hotel Exe Domus Aurea, Via Volturno 34, Roma",
    "lat": 41.9043759,
    "lng": 12.5000161,
    "mapSource": "https://www.openstreetmap.org/node/9961065859",
    "url": "https://www.eurostarshotels.co.uk/exe-domus-aurea.html",
    "bookingSource": "https://www.expedia.it/Rome-Hotel-EXE-Domus-Aurea.h571337.Informazioni-Hotel?chkin=2026-10-03&chkout=2026-10-04&rm1=a1",
    "desc": "10/3–4 1인 · 조식 포함 싱글 11m², 미예약. 10/1 08:23–08:31 UTC Expedia 조회: 총 €286(예약 시 €280 + 현장 도시세 €6), 환불 불가. 24시간 프런트, 체크인 15:00 이후 / 체크아웃 12:00, 일요일 조식 07:00–11:00. Expedia는 엘리베이터 없음 / Agoda는 있음으로 안내가 충돌. 23kg 짐 이동·계단·객실 접근성을 호텔에 확인해야 하므로 후순위. 요금·최종 조건 재확인."
  },
  {
    "id": "piccolo-arancio",
    "city": "rome",
    "name": "Piccolo Arancio · 저녁 우선",
    "category": "food",
    "area": "Vicolo Scanderbeg 112",
    "address": "Piccolo Arancio, Vicolo Scanderbeg 112, Roma",
    "lat": 41.9009004,
    "lng": 12.484951,
    "desc": "10/3 체크인 후 저녁 추천, 미예약. 공식 화–일 18:30–24:00(영업 종료와 주방 주문 마감은 다를 수 있음). 로마 파스타 일부 €15–16, 다른 메뉴는 더 비쌀 수 있음. 늦게 도착하면 주방·좌석 확인 후 방문.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.piccoloarancio.it/en/",
    "mapSource": "https://www.openstreetmap.org/node/5288226321"
  },
  {
    "id": "baccano",
    "city": "rome",
    "name": "Baccano · 점심 우선",
    "category": "food",
    "area": "Via delle Muratte 23",
    "address": "Baccano, Via delle Muratte 23, Roma",
    "lat": 41.9003672,
    "lng": 12.4823634,
    "desc": "10/4 12:30–13:00 점심 추천, 미예약. 파스타 €17–22 정도(조회 메뉴 기준, 최신 가격 확인). 호텔 짐 회수와 연결하기 쉬운 Trevi 인근. 13:45 전후 식사 종료를 목표로, 좌석·운영은 방문 전 확인.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.baccanoroma.com/menu",
    "mapSource": "https://www.openstreetmap.org/node/2273987475"
  },
  {
    "id": "chianti",
    "city": "rome",
    "name": "Il Chianti · 저녁 대안",
    "category": "food",
    "area": "Via del Lavatore 81/82/82A",
    "address": "Il Chianti, Via del Lavatore 81/82/82A, Roma",
    "lat": 41.9011813,
    "lng": 12.48414,
    "desc": "Trevi 가까운 토스카나 식당·와인 대안, 미예약. 핀은 OSM 82번 업장 기준. 늦은 저녁 주방 주문 가능 여부와 좌석을 확인. Piccolo Arancio와 둘 중 한 곳만 선택.",
    "day": "10.3",
    "status": "후보",
    "url": "https://chiantiosteriatoscana.it/",
    "mapSource": "https://www.openstreetmap.org/node/1988966799"
  },
  {
    "id": "piccolo-buco",
    "city": "rome",
    "name": "Piccolo Buco · 피자 대안",
    "category": "food",
    "area": "Via del Lavatore 91",
    "address": "Piccolo Buco, Via del Lavatore 91, Roma",
    "lat": 41.9013051,
    "lng": 12.4846318,
    "desc": "피자 일부 €13–17 정도(조회 메뉴 기준). 예약을 받지 않는 현장 대기 식당. 도착이 늦거나 줄이 길면 다른 식당으로 변경. 영업·주방 마감 재확인.",
    "day": "10.3",
    "status": "후보",
    "url": "https://pizzeriapiccolobuco.it/en/",
    "mapSource": "https://www.openstreetmap.org/node/3190236550"
  },
  {
    "id": "luna",
    "city": "rome",
    "name": "Luna by Faro · 외부 아침",
    "category": "coffee",
    "area": "Via delle Quattro Fontane 175",
    "address": "Luna by Faro, Via delle Quattro Fontane 175, Roma",
    "lat": 41.9031513,
    "lng": 12.4884949,
    "desc": "스페셜티 커피·브런치 아침 후보, 미예약. 공식 하단은 토·일 08:00–19:00, 상단은 17:00 마감으로 달라 영업 재확인. 10/4 08:30–09:15 아침 제안, 공휴일 운영 미확인. 포함 조식을 이용하면 생략.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.lunabyfaro.com/web/",
    "mapSource": "https://www.openstreetmap.org/node/13110571701"
  },
  {
    "id": "trecaffe",
    "city": "rome",
    "name": "TreCaffè Due Macelli · 아침 대안",
    "category": "coffee",
    "area": "Via dei Due Macelli 107",
    "address": "TreCaffè Due Macelli, Via dei Due Macelli 107, Roma",
    "lat": 41.9033232,
    "lng": 12.4851429,
    "desc": "Memphis와 Spagna 사이의 커피·외부 아침 대안. Luna 또는 포함 조식과 하나만 선택. 방문일 아침 운영·메뉴 재확인, 미예약.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.trecaffe.it/",
    "mapSource": "https://www.openstreetmap.org/node/9896970933"
  },
  {
    "id": "santeustachio",
    "city": "rome",
    "name": "Sant’Eustachio Il Caffè · Pantheon 대안",
    "category": "coffee",
    "area": "Piazza Sant’Eustachio 82",
    "address": "Sant’Eustachio Il Caffè, Piazza Sant’Eustachio 82, Roma",
    "lat": 41.8982524,
    "lng": 12.4754268,
    "desc": "Pantheon 외관 코스를 선택할 때 커피 대안. Spagna·쇼핑·Pincio 코스에 모두 추가하지 않고 교체하는 선택지. 미예약·공휴일 운영 재확인.",
    "day": "10.4",
    "status": "후보",
    "url": "https://santeustachioilcaffe.com/",
    "mapSource": "https://www.openstreetmap.org/node/261859088"
  },
  {
    "id": "rinascente",
    "city": "rome",
    "name": "Rinascente Tritone",
    "category": "shop",
    "area": "Via del Tritone 61",
    "address": "Rinascente Tritone, Via del Tritone 61, Roma",
    "lat": 41.9027186,
    "lng": 12.4847351,
    "desc": "의류·디자인·기념품 백화점. 짧게 쇼핑할 1–2곳 중 하나. 10/4는 2026년부터 국가 공휴일: 해당 날짜 특별 영업 미확인, 문이 닫혀 있으면 산책으로 변경.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.rinascente.it/it/store-roma-via-del-tritone/",
    "mapSource": "https://www.openstreetmap.org/node/5288226122"
  },
  {
    "id": "ovs-tritone",
    "city": "rome",
    "name": "OVS Tritone",
    "category": "shop",
    "area": "Via del Tritone 172",
    "address": "OVS Tritone, Via del Tritone 172, Roma",
    "lat": 41.9024646,
    "lng": 12.4846932,
    "desc": "부담 적은 의류 쇼핑 대안. 공식 통상 일요일 10:00–20:00, 10/4 공휴일 특별 영업 미확인. Rinascente 등과 1–2곳만 선택.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.ovs.it/it/it/stores/italia/lazio/roma/ovs-roma-tritone",
    "mapSource": "https://www.openstreetmap.org/node/4450577283"
  },
  {
    "id": "doppelganger",
    "city": "rome",
    "name": "Doppelgänger Tritone",
    "category": "shop",
    "area": "Via del Tritone 128–131",
    "address": "Doppelgänger Tritone, Via del Tritone 128–131, Roma",
    "lat": 41.9031146,
    "lng": 12.4873246,
    "desc": "남성 의류·액세서리 쇼핑 대안. 공식 통상 일요일 09:30–20:00, 10/4 공휴일 특별 영업 미확인. 좌표는 공식 매장의 Google Maps 링크 목적지 기준.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.doppelganger.it/en-us/store/roma-tritone.html",
    "mapSource": "https://www.doppelganger.it/en-us/store/roma-tritone.html"
  },
  {
    "id": "fabriano",
    "city": "rome",
    "name": "Fabriano Boutique",
    "category": "shop",
    "area": "Via del Babuino 173",
    "address": "Fabriano Boutique, Via del Babuino 173, Roma",
    "lat": 41.9090534,
    "lng": 12.4781071,
    "desc": "문구·노트·종이 기념품 대안. Spagna·Via Margutta 방향에서 선택. 공식 통상 일요일 10:00–20:00, 10/4 공휴일 특별 영업 미확인. 좌표는 공식 매장 안내 데이터 기준.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.fabrianoboutique.com/fabriano_it/amlocator",
    "mapSource": "https://www.fabrianoboutique.com/fabriano_it/amlocator"
  },
  {
    "id": "castroni",
    "city": "rome",
    "name": "Castroni Frattina · 휴일 주의",
    "category": "shop",
    "area": "Via Frattina 79",
    "address": "Castroni Frattina, Via Frattina 79, Roma",
    "lat": 41.9037493,
    "lng": 12.4796709,
    "desc": "커피·식품 기념품 대안. 공휴일 휴무 안내가 있어 10/4 필수 방문에서 제외. 해당 지점 운영 확인 시에만 들르기.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.castronicoladirienzoshop.com/",
    "mapSource": "https://www.openstreetmap.org/node/5061626621"
  },
  {
    "id": "spagna",
    "city": "rome",
    "name": "Piazza di Spagna · 핵심 산책",
    "category": "sight",
    "area": "Piazza di Spagna",
    "address": "Piazza di Spagna, Piazza di Spagna, Roma",
    "lat": 41.9056392,
    "lng": 12.482358,
    "desc": "체크아웃·짐 보관 후 핵심 산책. Via Margutta까지 걷고 쇼핑 또는 Popolo/Pincio 중 하나를 선택. 핀은 광장 대표점.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.turismoroma.it/en/places/piazza-di-spagna",
    "mapSource": "https://www.openstreetmap.org/relation/13474926"
  },
  {
    "id": "margutta",
    "city": "rome",
    "name": "Via Margutta · 핵심 산책",
    "category": "sight",
    "area": "Via Margutta",
    "address": "Via Margutta, Via Margutta, Roma",
    "lat": 41.9086166,
    "lng": 12.4795284,
    "desc": "Spagna에서 이어지는 조용한 골목 산책. 핀은 거리 대표점. 이후 짧은 쇼핑 또는 Popolo/Pincio 전망 산책 중 하나 선택.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.turismoroma.it/en/places/margutta-street",
    "mapSource": "https://www.openstreetmap.org/way/203960577"
  },
  {
    "id": "popolo",
    "city": "rome",
    "name": "Piazza del Popolo · 전망 코스",
    "category": "sight",
    "area": "Piazza del Popolo",
    "address": "Piazza del Popolo, Piazza del Popolo, Roma",
    "lat": 41.9107479,
    "lng": 12.4763646,
    "desc": "쇼핑 대신 전망 산책을 선택할 때 들를 광장. Pincio 방향 오르막·계단과 점심 복귀 여유를 고려. 핀은 광장 대표점.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.turismoroma.it/en/places/piazza-del-popolo",
    "mapSource": "https://www.openstreetmap.org/relation/318583"
  },
  {
    "id": "pincio-terrace",
    "city": "rome",
    "name": "Terrazza del Pincio · 선택 전망",
    "category": "sight",
    "area": "Terrazza del Pincio, Salita del Pincio",
    "address": "Terrazza del Pincio, Terrazza del Pincio, Salita del Pincio, Roma",
    "lat": 41.911316,
    "lng": 12.477798,
    "desc": "Popolo와 연결되는 낮 전망 산책. 좌표는 로마 관광청의 전망대·산책로 대표 위치. 실제 접근은 도보 길찾기 확인. 쇼핑과 함께 전부 넣지 않고 하나만 선택.",
    "day": "10.4",
    "status": "후보",
    "url": "https://www.turismoroma.it/en/places/pincio-terrace-and-promenade",
    "mapSource": "https://www.turismoroma.it/en/places/pincio-terrace-and-promenade"
  },
  {
    "id": "quirinale",
    "city": "rome",
    "name": "Piazza del Quirinale · 야경 확장",
    "category": "sight",
    "area": "Piazza del Quirinale",
    "address": "Piazza del Quirinale, Piazza del Quirinale, Roma",
    "lat": 41.899348,
    "lng": 12.4864817,
    "desc": "저녁·Trevi 후 체력이 남을 때만 선택하는 광장 외관 산책. 늦은 도착이면 생략하고 Memphis로 복귀. 핀은 광장 대표점.",
    "day": "10.3",
    "status": "후보",
    "url": "https://www.turismoroma.it/en/places/piazza-del-quirinale",
    "mapSource": "https://www.openstreetmap.org/way/516174441"
  }
];
const BARI_CANDIDATES=[
  {
    "id": "bari-moderno",
    "city": "bari",
    "name": "Hotel Moderno · 예약 완료",
    "category": "stay",
    "area": "Via Scipione Crisanzio 60 · Murat",
    "address": "Hotel Moderno, Via Scipione Crisanzio 60, Bari",
    "lat": 41.1195168,
    "lng": 16.8651418,
    "mapSource": "https://www.openstreetmap.org/node/2882564521",
    "url": "https://www.modernobari.com/",
    "day": "10.4",
    "status": "예약 완료",
    "desc": "2026/10/4–5 성인 1인 1박 · 결제 승인·호텔 확인 메일로 예약 확정. Superior Single · 전용 욕실 · 조식 포함. 총 €142.80(현장 도시세 €2 포함), 환불·변경 불가. 예상 체크인 21시(도착 보장 시각 아님), 체크아웃 11시. 10/4 Bari Centrale 20:20 도착 → Hotel Moderno → 저녁. 10/5 조식·시내 산책 → 11시 전 체크아웃·짐 보관 → 점심·짐 회수 → 택시로 Nicolaus 13시 도착 목표 → GEMINI 14시 참석 예정 후보. 24시간 프런트·엘리베이터·짐 보관 안내; 체크아웃 후 보관 시간·비용은 호텔에 확인."
  },
  {
    "id": "bari-victor",
    "city": "bari",
    "name": "Victor Hotel · 추가 1박 대안",
    "category": "stay",
    "area": "Via Domenico Nicolai 71 · Murat",
    "address": "Victor Hotel, Via Domenico Nicolai 71, Bari",
    "lat": 41.1212966,
    "lng": 16.8662208,
    "mapSource": "https://www.openstreetmap.org/node/13790588001",
    "url": "https://www.victorhotelbari.it/",
    "day": "10.4",
    "status": "후보",
    "desc": "10/4–5 성인 1인 1박 · 미선택·미예약. 10/2 조회 총 €168 · 더블침대 · 전용 욕실 · 조식 포함. 선결제·환불 불가. 24시간 프런트·엘리베이터·짐 보관, 체크아웃 10시. 10/4 열차 도착 후 숙박 → 10/5 일찍 체크아웃·짐 보관 후 시내 산책 → 점심·짐 회수 → 택시로 Nicolaus 이동. 요금·객실·최종 조건 변동 가능; 짐 보관 시간·비용 확인."
  },
  {
    "id": "bari-boston",
    "city": "bari",
    "name": "Hotel Boston · 추가 1박 대안",
    "category": "stay",
    "area": "Via Niccolò Piccinni 155 · Murat",
    "address": "Hotel Boston, Via Niccolò Piccinni 155, Bari",
    "lat": 41.1252417,
    "lng": 16.8648639,
    "mapSource": "https://maps.app.goo.gl/2x967rJu9p9w9kSf9",
    "url": "https://www.bostonbari.it/contatti-hotel-bari/",
    "day": "10.4",
    "status": "후보",
    "desc": "10/4–5 성인 1인 1박 · 미선택·미예약. 10/2 조회 총 €216.31 · 퀸 침대 · 18㎡ · 전용 욕실 · 조식 포함. 선결제·환불 불가. 24시간 프런트·엘리베이터·짐 보관, 체크아웃 11시. 시내·구시가지 접근을 고려하는 대안. 10/4 20:20 열차 도착 → 숙소 → 10/5 시내 아침·체크아웃·점심·짐 회수 → 택시로 Nicolaus 12:45–13시 목표. 요금·객실·최종 조건 변동 가능; 짐 보관 시간·비용 확인. 좌표는 호텔 공식 지도 링크 기준."
  }
];
