for(const p of PLACES){if(p.id==='mastrociccio'){p.day='10.4';p.url='https://www.mastrociccio.it/menu/';p.desc='미예약. Moderno 도보 약 18–20분 추정. 정규 일요일 10–23시(공식), 공휴일 실제 영업·주방 마감·좌석 미확인. UPulp 문어·부라타 샌드위치 €12, Nostrano 판체로토 €3, 치메 디 라파 오레키에테 €10.90.';}if(p.id==='mercantile-nove'){p.day='10.4';p.lat=41.1275462;p.lng=16.8713935;p.mapSource='https://www.openstreetmap.org/node/5092469027';p.address='Mercantile Nove, Piazza Mercantile 9, Bari, Italy';p.desc='미예약·선택 술집. MastroCiccio에서 약 4–5분, Moderno 복귀 약 20–25분 추정. 공식 메뉴 스프리츠 €6, 네그로니 €8, 풀리아 화이트·로제 잔 €5, 테이블 €2. 보조 안내 일요일 09–01시이나 공휴일 실제 영업·마감·좌석 미확인. Luau Tiki는 대체 후보이며 둘 다 방문할 필요 없음.';}}
const WALK_ROUTES=[
{"id":"revised-oct4","name":"10/4 대안 · 백화점 생략","stops":["colonna","pantheon","navona"],"morning":true,"taxi":true,"note":"09:55–10:05 Memphis 체크아웃·짐 보관(호텔 허가 확인, 실제 맡김 완료 미확인) → 10:05–11:00 Rinascente Tritone → Colonna → Pantheon 11:15–11:45 → Navona 11:50–12:15 → Emma 12:30–13:40(미예약) → 13:40까지 출발 → 도보 약 30분 추정, 14:15 Memphis 목표 → 14:15–14:30 짐 회수 → 택시로 Termini 15:15 목표 → FR8317 15:57. 시각·도보시간은 계획용 추정."},
{"id":"revised-oct4-shop","name":"10/4 오늘 동선 · Rinascente → Pantheon → Navona → Emma","stops":["rinascente","colonna","pantheon","navona"],"morning":true,"taxi":true,"note":"09:55–10:05 Memphis 체크아웃·짐 보관(호텔 허가 확인, 실제 맡김 완료 미확인) → 10:05–11:00 Rinascente Tritone → Colonna → Pantheon 11:15–11:45 → Navona 11:50–12:15 → Emma 12:30–13:40(미예약) → 13:40까지 출발 → 도보 약 30분 추정, 14:15 Memphis 목표 → 14:15–14:30 짐 회수 → 택시로 Termini 15:15 목표 → FR8317 15:57. 시각·도보시간은 계획용 추정."},
 {id:'return-home',name:'10/8 귀국 · Nicolaus → Bari → Roma → FCO',stops:['nicolaus','bari-station','termini','fco'],note:'택시·열차 이동 순서. 실제 운행 경로가 아닌 개략 연결선.'},
 {id:'memphis-night',name:'10/3 핵심 · 저녁 → Trevi → Memphis',stops:['trevi'],returnHotel:true,note:'21–22시 체크인 예상 후 저녁 → 22:30–23:15 Trevi 외부 야경 → 호텔 복귀. 시각은 계획 예시이며 입국·수하물·교통 상황에 따라 변경. 늦으면 식당 주방 확인, 체력이 없으면 야경도 생략.'},
 {id:'memphis-night-plus',name:'10/3 선택 확장 · Trevi → Quirinale',stops:['trevi','quirinale'],returnHotel:true,note:'핵심 야경 후 체력이 남을 때만 Quirinale 광장 외관 추가. 늦은 도착이면 핵심 코스만 선택.'},
 {id:'morning-shop',name:'이전 대안 · 10/4 A · Spagna·Margutta + 짧은 쇼핑',stops:['spagna','margutta','rinascente'],morning:true,note:'09:45–10:15 체크아웃·짐 보관(늦어도 11시 전) → Spagna·Via Margutta → 1–2곳만 쇼핑 → 12:30–13시 점심 → 14시 전후 호텔 짐 회수 → Termini 15:15 목표. 기본 지도는 Rinascente 1곳만 경유. Fabriano·OVS·Doppelgänger는 교체 후보, 모두 방문하는 계획 아님. 공휴일 운영 미확인; 닫으면 산책으로 변경.'},
 {id:'morning-view',name:'이전 대안 · 10/4 B · Spagna·Margutta + Popolo·Pincio',stops:['spagna','margutta','popolo','pincio-terrace'],morning:true,note:'쇼핑 대신 전망 산책. 체크아웃·짐 보관 후 Spagna → Via Margutta → Popolo → Pincio → 12:30–13시 점심 → 14시 전후 Memphis 짐 회수 → Termini 15:15 목표. 오르막·계단 포함, 피곤하거나 늦으면 전망대를 생략. 실제 길찾기 시간에 맞춰 일찍 출발.'},
 {id:'morning-pantheon',name:'이전 대안 · 10/4 C · Pantheon 외관·커피로 교체',stops:['pantheon','santeustachio'],morning:true,note:'Spagna·쇼핑·Pincio를 대신하는 대안. Pantheon 외관 + Sant’Eustachio 커피 → 점심 → 호텔 짐 회수 → Termini. 내부 입장 예약 없음; 다른 오전 코스에 모두 추가하지 않기.'},
 {id:'central',name:'중심가 · Navona → Pantheon → Trevi',stops:['navona','pantheon','trevi'],note:'10/3 야경 후보. Camillo·MONS와 연결하기 좋은 중심가 동선. 외관·광장 산책이며 미확정.'},
 {id:'tiber',name:'Tiber · Castel → St Peter',stops:['castel','conciliazione','stpeter'],note:'10/3 야경 후보. 강변과 St Peter 외관. 내부 입장 계획 아님, 현장 접근·보안 통제 확인.'},
 {id:'trastevere',name:'Trastevere · Santa Maria → Ponte Sisto',stops:['santamaria','trilussa','pontesisto'],note:'10/3 야경 후보. Trapizzino·Trilussa와 연결. 골목·광장·보행교 중심.'},
 {id:'ancient',name:'고대 로마 · Colosseum → Campidoglio',stops:['colosseum','fori','campidoglio'],note:'10/3 야경 후보. Suburra·Cimarra 대안과 비교. 조명·공사·보행 통제 미확인.'},
 {id:'pincio',name:'Pincio 공원 · 후순위',stops:['pincio'],note:'늦은 도착일에는 후순위. 핀은 공원 대표점, 전망대 출입구가 아님. 오르막·야간 접근 확인.'},
 {id:'departure',name:'10/4 · 점심 → 호텔 짐 회수 → Termini',stops:['termini'],note:'계획용 버퍼: 점심 12:30–13:45 → 짐 회수 14:00–14:30 → 역 이동 14:45 → Termini 15:15–15:25 도착 목표 → FR8317 15:57 출발. 실제 이동시간이 아닌 여유 목표이며, 호텔·점심 위치와 길찾기 결과에 맞춰 조정.'}
];
WALK_ROUTES.push(...[{"id":"bari-full","name":"10/4 · La Uascézze 저녁 → 호텔","stops":["bari-moderno","uascezze","bari-moderno"],"bari":true},{"id":"bari-full-drink","name":"10/4 · La Uascézze → 선택 Mercantile Nove","stops":["bari-moderno","uascezze","mercantile-nove","bari-moderno"],"bari":true},{"id":"bari-quick","name":"10/4 · MastroCiccio → 선택 Mercantile Nove","stops":["bari-moderno","mastrociccio","mercantile-nove","bari-moderno"],"bari":true},{"id":"bari-tiki","name":"10/4 · MastroCiccio → 선택 Luau Tiki","stops":["bari-moderno","mastrociccio","luau-tiki","bari-moderno"],"bari":true},{"id":"bari-near","name":"10/4 · 가까운 Yannis → 호텔","stops":["bari-moderno","yannis-centro","bari-moderno"],"bari":true}]);
WALK_ROUTES.push(...[{"id":"bari-note","name":"10/6–7 · Nicolaus → Note Di Vino → 호텔","stops":["nicolaus","note-di-vino","nicolaus"],"bari":true},{"id":"bari-numeri","name":"10/6–7 · Nicolaus → Numeri Primi → 호텔","stops":["nicolaus","numeri-primi","nicolaus"],"bari":true},{"id":"bari-gulp","name":"10/6–7 · Nicolaus → Gulp → 호텔","stops":["nicolaus","gulp","nicolaus"],"bari":true}]);
let courseActive=true;
let routeChoice='revised-oct4-shop',routeHotel='memphis',routeDinner='piccolo-arancio',routeLunch='emma',routeExpanded=false;
try{const prefs=JSON.parse(localStorage.getItem('italia-route-view-v1')||'{}');if(WALK_ROUTES.some(r=>r.id===prefs.route)&&!['morning-shop','morning-view','morning-pantheon','revised-oct4'].includes(prefs.route))routeChoice=prefs.route;routeHotel=prefs.hotel||'memphis';routeDinner=prefs.dinner||'piccolo-arancio';routeLunch=routeChoice.startsWith('revised-oct4')?'emma':prefs.lunch||'emma'}catch{}
function routePoints(){
 if(routeChoice.startsWith('bari-'))return WALK_ROUTES.find(r=>r.id===routeChoice).stops.map(id=>findPlace(id));
 if(routeChoice==='return-home')return ['nicolaus','bari-station','termini','eataly-termini','fco','aelia-fco'].map(id=>findPlace(id));
 const r=WALK_ROUTES.find(r=>r.id===routeChoice),hotel=findPlace(routeHotel),departure=r.id==='departure',meal=findPlace(departure||r.morning?routeLunch:routeDinner),points=[];
 if(hotel)points.push({...hotel,routeLabel:hotel.name+(r.morning?' · 체크아웃·짐 보관':' · 출발')});
 if(meal&&!r.morning)points.push({...meal,routeLabel:meal.name+(departure?' · 점심 추천 (미예약)':' · 저녁 추천 (미예약)')});
 for(const id of r.stops){const p=findPlace(id);if(p&&id!=='termini')points.push(p)}
 if(r.morning&&meal)points.push({...meal,routeLabel:meal.name+(r.taxi?' · 12:30 점심 / 13:40까지 출발 (미예약)':' · 12:30–13시 점심 추천 (미예약)')});
 if((departure||r.morning||r.returnHotel)&&hotel)points.push({...hotel,routeLabel:hotel.name+(departure||r.morning?(r.taxi?' · 14:15–14:30 짐 회수':' · 14시 전후 짐 회수')+(hotel.id==='memphis'?' (무료 보관)':' (보관 조건 확인)'):' · 복귀')});
 if(departure||r.morning){const p=findPlace('termini');points.push({...p,routeLabel:'Termini · 15:15 목표 / FR8317 15:57 출발'})}
 return points;
}
function walkingChunks(points){
 const chunks=[];for(let i=0;i<points.length-1;i+=4)chunks.push(points.slice(i,i+5));
 return chunks.length?chunks:[points];
}

function returnPlanHTML(){return '<details class="return-plan" '+(dayFilter==='10.8'?'open':'')+'><summary><b>10/8 목 · 귀국 시간·이동</b><span>FR8306 발권 완료 / TW406 21:15 FCO T3 확정</span></summary><ol class="day-timeline"><li><b>07:50 출발 → 08:10 역 도착 목표</b> Nicolaus 조기 체크아웃 → 택시로 Bari Centrale. 숙박 예약은 10/5–9 유지; 조기 출발 통지·환불·예약 변경 완료 미확인. 10/8 오전 출발 이후 학회 참석 계획 없음.</li><li><b>08:40 → 13:15 발권 완료</b> 10/8 FR8306 Bari Centrale → Roma Termini · BASE/STANDARD · 발권 완료. 기존 10/9 표는 교환되어 대체되었으며 현재 이용 일정이 아닙니다.</li><li><b>13:15 이후 역 실내 점심·쇼핑</b> Eataly 소매점(승강장층)·역 안 점심·휴식. 캐리어와 인파 부담을 줄여 로마 시내 추가 방문 없이 공항 이동. Sassicaia는 같은 매장에 있으면 가격을 보고, 없으면 생략.</li><li><b>16:30–17:15 무렵 공항 이동 계획</b> Leonardo Express 통상 32분·€14 · 공개 시간표 예 16:05→16:37 또는 16:35→17:07, 선택 후보·미구매. 통상 23/24 플랫폼, 전광판 우선. FCO 약 17:15 도착 목표, 늦어도 18:15 목표에 맞춰 실제 편 선택.</li><li><b>FCO T3 수속</b> 터미널 이동·체크인·짐 위탁·보안검색·출국 수속. 공식 카운터 18:45–20:25, T3(406–411 변동 가능). 일찍 도착해도 위탁 캐리어를 바로 맡기거나 면세점에 들어갈 수 있다고 전제하지 마세요. 출국 수속 후 E구역 Aelia/La Bottega dei Sapori, Bongustare는 선택 보충. 영업·재고·가격 미확인.</li><li><b>확정 TW406 · 10/8 21:15 FCO T3 → 10/9 16:10 ICN T1</b> 출발은 Europe/Rome CEST(UTC+2), 도착은 Asia/Seoul KST(UTC+9). 한국 도착은 다음 날.</li></ol><p class="route-warning">10/6–23 공항철도 일부 변경·취소·대체버스 공지: 당일 운행을 확인하고 필요하면 로마 휴식을 줄여 공항 이동을 앞당기세요.</p><button type="button" class="plan-route-button" data-plan-route="return-home">10/8 귀국 이동 순서 지도에 보기</button> <a class="plan-source" href="https://www.trenitalia.com/it/informazioni/lavori-programmati/20261006-linee-roma-termini-fiumicino-aeroporto-roma-velletri-roma-pisa.html" target="_blank" rel="noopener">공항철도 공식 변경 공지 ↗</a> '+sourceLink('https://www.trenitalia.com/content/dam/trenitalia/allegati/info/orario-digitale/collegamenti/orari-leonardo-express.pdf','LE 시간표')+sourceLink('https://www.trinityairways.com/app/serviceInfo/airportCounter?deptAirport=FCO+%EB%A1%9C%EB%A7%88%2F%EB%8B%A4%EB%B9%88%EC%B9%98&airportCode=FCO','공식 FCO 카운터 안내')+'</details>';}

function renderReturnRoute(fit){
 const panel=$('#routeWorkspace');panel.hidden=false;const points=routePoints();routeLayer.clearLayers();
 const driving=new URL(walkingLink(points.slice(0,2)));driving.searchParams.set('travelmode','driving');driving.searchParams.set('destination','Bari Centrale, Bari, Italy');
 panel.innerHTML='<div class="route-heading"><strong>10/8 귀국 · 역·공항 쇼핑만</strong></div><ol class="route-stops">'+points.map((p,i)=>'<li><button type="button" data-route-place="'+p.id+'"><b>'+(i+1)+'</b><span>'+escapeHTML(p.name)+'</span></button></li>').join('')+'</ol><div class="route-links"><a href="'+escapeHTML(driving.href)+'" target="_blank" rel="noopener">Nicolaus → 역 차량 길찾기 ↗</a><a href="https://www.trenitalia.com/en.html" target="_blank" rel="noopener">열차 운행·시간표 확인 ↗</a></div><p class="route-disclaimer">점선은 도시 간 이동 순서이며 실제 도로·철도·실내 보행 경로가 아닙니다. 역·공항 매장은 대표 핀이고 같은 좌표는 실내 이동을 뜻하지 않습니다. Nicolaus→Bari 역은 택시, Bari→Roma는 10/8 FR8306 발권 완료, Roma→FCO는 추천 공항철도(미구매)입니다.</p><button type="button" class="plan-route-button" data-plan-route="memphis-night">10/3 로마 동선으로 돌아가기</button>';
 L.polyline(points.filter((p,i)=>i===0||p.lat!==points[i-1].lat||p.lng!==points[i-1].lng).map(p=>[p.lat,p.lng]),{color:'#bd762e',weight:3,dashArray:'5,8',opacity:.8,interactive:false}).addTo(routeLayer);
 points.forEach((p,i)=>L.marker([p.lat,p.lng],{icon:L.divIcon({className:'',html:'<span class="route-pin">'+(i+1)+'</span>',iconSize:[30,30],iconAnchor:[15,15]}),title:(i+1)+'. '+p.name}).addTo(routeLayer).on('click',()=>{if(!picking)selectPlace(p.id)}));
 if(fit)map.fitBounds(points.map(p=>[p.lat,p.lng]),{padding:[40,45]});
}


function eveningPlanHTML(){
 return '<details class="daily-plan" open><summary><b>10/4 저녁 후보 기록 · Moderno 체크인 완료</b><span>20:55 출발 계획 · 식당·바 모두 미예약</span></summary><p class="route-note">풀 저녁은 La Uascézze, 빠른 식사는 MastroCiccio, 가까운 대안은 Yannis 중 하나를 선택하세요. 술은 Mercantile Nove 또는 Luau Tiki 중 선택이며 필수가 아닙니다. 식당을 차례로 모두 방문하는 코스가 아닙니다.</p><div class="plan-branch-buttons">'+WALK_ROUTES.filter(r=>r.bari).map(r=>'<button type="button" data-plan-route="'+r.id+'">'+escapeHTML(r.name)+'</button>').join('')+'</div><p class="route-note">La Uascézze: 밥·감자·홍합 €10 / 잠두·치커리 €9 / 브라촐레 €16 / 공휴일 서비스 €3 · 식사 약 €25–35 추정.<br>MastroCiccio: UPulp 문어·부라타 샌드위치 €12 / Nostrano 판체로토 €3 / 치메 디 라파 오레키에테 €10.90.<br>Yannis: 피타 기로스 €6.50 / 무사카 €10 / 커버 €2.<br>Mercantile Nove: 스프리츠 €6 / 네그로니 €8 / 풀리아 와인 잔 €5 / 테이블 €2.<br>Luau Tiki: 럼·티키 칵테일, 공식 가격 미표기.</p><div class="plan-small-links">'+['uascezze','mastrociccio','yannis-centro','mercantile-nove','luau-tiki'].map(id=>{const p=findPlace(id);return '<a href="'+escapeHTML(p.url)+'" target="_blank" rel="noopener">'+escapeHTML(p.name)+' · 공식 메뉴 ↗</a>'}).join('')+'</div><p class="route-warning">정규 일요일 시간은 공휴일 영업 보장이 아닙니다. 10/4 실제 영업·주방 마지막 주문·좌석은 미확인입니다. 20:55 출발·이동시간은 계획용 추정이며 La Uascézze 도착 약 21:15–21:20 목표. Luau 핀은 거리 대표 위치로 정확한 입구는 주소 길찾기로 확인하세요.</p></details>';
}
function renderBariEvening(fit){
 const panel=$('#routeWorkspace');panel.hidden=false;routeLayer.clearLayers();const r=WALK_ROUTES.find(r=>r.id===routeChoice),points=routePoints();
 panel.innerHTML='<div class="route-heading"><strong>'+escapeHTML(r.name)+'</strong><span>선택 후보 · 방문·구매 미완료</span></div><label class="route-label">쇼핑·식사 선택 코스<select id="routeChoice">'+WALK_ROUTES.filter(x=>x.bari).map(x=>'<option value="'+x.id+'" '+(routeChoice===x.id?'selected':'')+'>'+escapeHTML(x.name)+'</option>').join('')+'</select></label><p class="route-note">마지막 번호는 출발 호텔 복귀입니다. 술집은 선택 사항: 생략하려면 저녁만 코스를 선택하세요. Ferrarese·Mercantile 광장은 여유가 있을 때 산책하는 별도 후보입니다.</p><ol class="route-stops">'+points.map((p,i)=>'<li><button type="button" data-route-place="'+p.id+'"><b>'+(i+1)+'</b><span>'+escapeHTML(p.name)+(i===0?' · 출발':i===points.length-1?' · 복귀':'')+'</span></button></li>').join('')+'</ol><div class="route-links"><a href="'+escapeHTML(walkingLink(points))+'" target="_blank" rel="noopener">호텔 왕복 도보 길찾기 ↗</a></div><details class="route-leg-details"><summary>구간별 길찾기</summary>'+points.slice(1).map((p,i)=>'<a href="'+escapeHTML(walkingLink([points[i],p]))+'" target="_blank" rel="noopener">'+(i+1)+' → '+(i+2)+' '+escapeHTML(p.name)+' ↗</a>').join('')+'</details><p class="route-disclaimer">연결선은 방문 순서이며 실제 보행 경로가 아닙니다. 공휴일 영업·주방 마감·좌석 미확인. Luau는 거리 대표 핀이며 길찾기는 가게 주소를 사용합니다.</p>';
 L.polyline(points.map(p=>[p.lat,p.lng]),{color:'#bd762e',weight:3,dashArray:'5,8',opacity:.8,interactive:false}).addTo(routeLayer);
 points.forEach((p,i)=>L.marker([p.lat,p.lng],{icon:L.divIcon({className:'',html:'<span class="route-pin">'+(i+1)+'</span>',iconSize:[30,30],iconAnchor:[15,15]}),title:(i+1)+'. '+p.name,zIndexOffset:500+i}).addTo(routeLayer).on('click',()=>{if(!picking)selectPlace(p.id)}));
 if(fit)map.fitBounds(points.map(p=>[p.lat,p.lng]),{padding:[40,45],maxZoom:15});
}


function sourceLink(url,label){return '<a class="plan-source" href="'+escapeHTML(url)+'" target="_blank" rel="noopener">'+escapeHTML(label)+' ↗</a>';}
function currentBariHTML(){return '<details class="daily-plan" open><summary><b>10/6–7 · 학회·가까운 쇼핑</b><span>이동·참석 예정 / 실제 완료 미확인</span></summary><ol class="day-timeline"><li><b>10/6 14:00–17:45 XRMemory</b> Sezione 6+7 참석 예정. Bowman keynote 14:15–14:45, 그룹토론 16:15–17:45. 오전 AdaptiveXR 실제 참석 미확인.</li><li><b>10/7 포스터 10:30–12:45</b> Cassiopea 9. 10:30 전 설치 필수, keynote 참석 시 09:30 전 설치 추천. 12:45 정리는 다음 세션 보드 재사용에 따른 추천이지 공식 마감 아님. Live teaser 없이 제출 영상 상영.</li><li><b>10/7 PS9 13:45–14:45</b> Sezione 1·마지막 발표, 개인 시작시각 미확인.</li><li><b>선택 쇼핑</b> Note Di Vino 도보 약 12분 추천 / Numeri Primi 약 5분·와인+오일. 오늘 18시 방문은 제안. 재고·가격 미확인. Vinarius·De Carlo는 별도 차량 이동 대안.</li></ol><div class="plan-branch-buttons">'+WALK_ROUTES.filter(r=>['bari-note','bari-numeri','bari-gulp'].includes(r.id)).map(r=>'<button type="button" data-plan-route="'+r.id+'">'+escapeHTML(r.name)+'</button>').join('')+'</div>'+sourceLink('https://xrmemory.org/workshop/ismar2026/','XRMemory 일정')+sourceLink('https://www.ieeeismar.net/2026/posters/','포스터 안내')+sourceLink('https://www.ieeeismar.net/2026/papers/','PS9 일정')+'</details><details class="daily-plan"><summary><b>호텔 식사·시설</b><span>공식 안내·현장 확인 필요</span></summary><p class="route-note">The Seasons 지상층: 조식 06:30–10:30 / 점심 12:30–14:30(FAQ 15시와 불일치) / 저녁 19:30–22:30. Gulp는 가까운 식사 후보·빈자리 미확인.<br>지하 2층 온수수영장·자쿠지·사우나·터키탕 화/수 15:30–20:30, 60분 예약·수영모 필요. 투숙객 무료 포함 여부 미확인. 헬스장 지하 2층: 이탈리아어 07–23 / 영문 19–23 불일치, 현장 확인. 무료 자전거 리셉션 요청. Nicolaus Connection PC·프린터 24시간, 출력비 미확인.</p>'+sourceLink('https://www.thenicolaushotel.com/en/hotel/faq','호텔 시설 FAQ')+'</details>';}

function renderTripOverview(){
 const panel=$('#tripOverview');panel.hidden=false;
 if(city==='bari'){panel.innerHTML=currentBariHTML()+'<div class="booked-heading"><span>10/4–5 확정 숙소</span><button type="button" data-route-place="bari-moderno">Hotel Moderno ↗</button></div><p class="booking-summary">성인 1인 · Superior Single · 전용 욕실 · 조식 포함<br>예약 확인 완료</p><p class="route-note"><b>10/4</b> Bari Centrale 20:20 도착 → Moderno 21시 체크인 예상 → 저녁. 도착시각은 교통·짐 이동에 따라 달라집니다.</p><p class="route-note"><b>10/5</b> 조식·시내 산책 → 11시 전 Moderno 체크아웃·짐 보관 → 점심·짐 회수 → 택시로 Nicolaus 13시 도착 목표 → 짐 보관 요청·배지 수령 → 13:45 행사장 → GEMINI 14:00–17:45 참석 예정 후보 → 종료 후 객실 체크인.</p><p class="route-note">Moderno 체크아웃 후 짐 보관 시간·비용, Nicolaus 체크인 전 짐 보관·월요일 등록데스크 시간은 확인 필요. Nicolaus 일반 체크인 15시부터, 조기 입실 보장 없음.</p>'+eveningPlanHTML()+returnPlanHTML();return;}
 const expanded=[...panel.querySelectorAll('.daily-plan')].map(d=>d.open);
 panel.innerHTML=`<div class="booked-heading"><span>확정 숙소</span><button type="button" data-route-place="memphis">Hotel Memphis ↗</button></div>
 <p class="booking-summary">10/3–4 · 예약 완료 · 조식 포함<br>Single Room / 전용 욕실</p>
 <p class="arrival-alert">체크인 14–23시 · 23시 이후 도착 예상 시 호텔에 연락</p>
 <details class="daily-plan"><summary><b>10/3 토 · 도착 → 저녁 → Trevi 야경</b><span>19:15 도착 / 21–22시 체크인 예상</span></summary>
 <ol class="day-timeline"><li><b>19:15</b> FCO 도착 → 입국·수하물 수령 → Leonardo Express로 Termini → Memphis. 마지막 구간은 짐·실제 도착시각에 맞춰 택시 또는 길찾기 확인.</li><li><b>21–22시 예상</b> 호텔 체크인. 도착 보장 시각이 아니며 지연 시 호텔에 연락.</li><li><b>체크인 후</b> Piccolo Arancio 우선, Il Chianti·Piccolo Buco는 대안. 모두 미예약; 늦으면 주방 주문 가능 여부 확인. 피자 대기가 길면 생략.</li><li><b>22:30–23:15 예시</b> Trevi 외부 야경 → Memphis 복귀. 외부는 무료; 내부 €2 구역(토·일 09–22시, 마지막 입장 21시)과 구분.</li></ol>
 <p class="route-note">핵심은 저녁과 Trevi. Quirinale 광장은 체력이 남을 때만 선택 확장.</p><button type="button" class="plan-route-button" data-plan-route="memphis-night">핵심 야경 동선 지도에 보기</button>
 <a class="plan-source" href="https://www.fontanaditrevi.roma.it/" target="_blank" rel="noopener">Trevi 공식 관람 안내 ↗</a></details>
 <details class="daily-plan"><summary><b>10/4 일 · Pantheon·Navona → Emma → 바리</b><span>09:55 체크아웃 시작 / Termini 15:15 목표</span></summary>
 <ol class="day-timeline"><li><b>09:00</b> 기상 → 포함 조식(07–10시)·짐 정리.</li><li><b>09:55–10:05</b> Memphis 체크아웃·짐 맡기기. 호텔의 짐 보관 허가는 확인됨; 실제 보관 완료는 아직 미확인. 14:15–14:30 회수 계획을 호텔에 알리기.</li><li><b>10:05–11:00</b> 첫 방문지 Rinascente Tritone, Via del Tritone 61. 패션·뷰티·식품 선물 둘러보기. 통상 10:00 개장, 공휴일 예외·현재 영업 여부 미확인. 닫혀 있으면 다음 동선으로 이동.</li><li><b>11:15–11:45 / 11:50–12:15 목표</b> Piazza Colonna 경유 → Pantheon 외관/Piazza della Rotonda → Piazza Navona. 전날 방문한 Spagna는 반복하지 않기. 판테온 내부는 첫 일요일 무료 현장 티켓·대기 가능, 일요일 10:30 미사로 방문 중단 가능. 기본은 외관이며 짧은 줄과 시간 여유가 있을 때만 입장.</li><li><b>12:30</b> Emma 점심 추천 · bufala Margherita €13 + supplì €4. 미예약·좌석 미확인, 공휴일 운영 재확인.</li><li><b>13:40까지 출발</b> Memphis까지 도보 약 30분 추정 → 14:15 호텔 도착 목표 → 14:15–14:30 짐 회수.</li><li><b>짐 회수 후</b> 택시로 Termini 15:15 도착 목표. 실제 교통·대기 상황에 맞춰 이동.</li><li><b>15:57 → 20:20</b> FR8317 Roma Termini → Bari Centrale · Standard/Base 예약·발권 완료. 10/4–5 Hotel Moderno 예약 완료. 20:20 역 도착 → 21시 체크인 예상 → 저녁.</li></ol>
 <p class="route-warning">10/4는 2026년부터 국가 공휴일. 매장 통상 일요일 영업이 당일 개장을 보장하지 않습니다. Castroni는 휴일 휴무 안내로 필수 동선 제외.</p>
 <div class="plan-branch-buttons"><button type="button" data-plan-route="revised-oct4">대안 · 백화점 생략</button><button type="button" data-plan-route="revised-oct4-shop">오늘 동선 · Rinascente 먼저</button></div>
 <div class="plan-small-links"><a href="${escapeHTML(walkingLink([findPlace('memphis'),findPlace('luna'),findPlace('memphis')]))}" target="_blank" rel="noopener">Luna 아침 왕복 ↗</a><a href="${escapeHTML(walkingLink([findPlace('memphis'),findPlace('trecaffe'),findPlace('memphis')]))}" target="_blank" rel="noopener">TreCaffè 아침 왕복 ↗</a></div>
 <p class="route-note">관광 시각은 계획용 여유 목표입니다. 식당·매장은 미예약, 현장 상황과 실제 이동시간에 맞춰 줄이세요.</p></details>`;
 panel.insertAdjacentHTML('beforeend',returnPlanHTML());
 panel.querySelectorAll('.daily-plan').forEach((d,i)=>{d.open=!!expanded[i]});
}
function walkingLink(points,mode='walking'){
 const u=new URL('https://www.google.com/maps/dir/');u.searchParams.set('api','1');u.searchParams.set('travelmode',mode);
 const address=p=>p.address||p.name+', '+(p.city==='rome'?'Roma':'Bari')+', Italy';
 if(points.length>1)u.searchParams.set('origin',address(points[0]));
 u.searchParams.set('destination',address(points[points.length-1]));
 if(points.length>2)u.searchParams.set('waypoints',points.slice(1,-1).map(address).join('|'));
 return u.href;
}
function routeOptions(ids,value,placeholder){return '<option value="">'+placeholder+'</option>'+ids.map(id=>{const p=findPlace(id);return p?'<option value="'+id+'" '+(value===id?'selected':'')+'>'+escapeHTML(p.name)+'</option>':''}).join('')}
function buildRoutes(fit=false){
 renderTripOverview();if(routeChoice==='return-home'){renderReturnRoute(fit);return;}if(city==='bari'){if(!routeChoice.startsWith('bari-'))routeChoice='bari-note';renderBariEvening(fit);return;}if(routeChoice.startsWith('bari-'))routeChoice='revised-oct4-shop';const panel=$('#routeWorkspace');panel.hidden=city!=='rome';routeLayer.clearLayers();if(city!=='rome')return;
 const r=WALK_ROUTES.find(r=>r.id===routeChoice),points=routePoints(),departure=routeChoice==='departure'||r.morning;
 panel.innerHTML='<div class="route-heading"><strong>동선 지도 · 선택 비교</strong><span>식당·관광은 미확정</span></div><label class="route-label">지도에서 비교할 코스<select id="routeChoice">'+WALK_ROUTES.filter(x=>!x.bari).map(x=>'<option value="'+x.id+'" '+(routeChoice===x.id?'selected':'')+'>'+escapeHTML(x.name)+'</option>').join('')+'</select></label>'+
 '<details id="routeDetails" '+(routeExpanded?'open':'')+'><summary>호텔·식당 연결과 순서 보기</summary><div class="route-fields"><label class="route-label">지도 비교 호텔 (확정: Memphis)<select id="routeHotel">'+routeOptions(['memphis','pace-helvezia','abruzzi','montecarlo','basilica','madison','virgilio','rome-times','exe-domus','raffaello','domus-harmonia','lancelot'],routeHotel,'미선택 · 코스만 보기')+'</select></label><label class="route-label">'+(departure?'점심 후보':'저녁 후보')+'<select id="'+(departure?'routeLunch':'routeDinner')+'">'+routeOptions(departure?['emma','baccano','piccolo-arancio','chianti','roscioli','felice','camillo','trapizzino']:['piccolo-arancio','chianti','piccolo-buco','baccano','camillo','mons','suburra','cimarra','trapizzino','mercato-centrale'],departure?routeLunch:routeDinner,'미선택 · 식사 제외')+'</select></label></div><p class="route-note">'+escapeHTML(r.note)+'</p>'+
 (departure&&!routeHotel?'<p class="route-warning">호텔을 선택하면 체크아웃 후 짐 회수 경유가 추가됩니다. 보관 가능 여부·비용·회수시간은 호텔 확인 필요.</p>':'')+
 (routeLunch==='roscioli'&&departure?'<p class="route-warning">Roscioli: 10/1 조회 시 10/4 1인 온라인 예약 불가. 실제 예약 없음.</p>':'')+
 '<ol class="route-stops">'+points.map((p,i)=>'<li><button type="button" data-route-place="'+p.id+'"><b>'+String(i+1).padStart(2,'0')+'</b><span>'+escapeHTML(p.routeLabel||p.name)+'</span></button></li>').join('')+'</ol>'+
 '<div class="route-links">'+walkingChunks(r.taxi?points.slice(0,-1):points).map((chunk,i)=>'<a href="'+escapeHTML(walkingLink(chunk))+'" target="_blank" rel="noopener">'+(points.length>5?'실제 도보 '+(i*4+1)+' → '+Math.min(i*4+5,r.taxi?points.length-1:points.length):'실제 도보 길찾기')+' ↗</a>').join('')+(!departure&&routeHotel&&!r.returnHotel?'<a href="'+escapeHTML(walkingLink([points[points.length-1],findPlace(routeHotel)]))+'" target="_blank" rel="noopener">코스 끝 → 호텔 ↗</a>':'')+'</div>'+
 '<details class="route-leg-details"><summary>구간별 길찾기</summary>'+points.slice(1).map((p,i)=>'<a href="'+escapeHTML(walkingLink([points[i],p],r.taxi&&i===points.length-2?'driving':'walking'))+'" target="_blank" rel="noopener">'+(i+1)+' → '+(i+2)+' '+escapeHTML(p.routeLabel||p.name)+(r.taxi&&i===points.length-2?' · 택시':'')+' ↗</a>').join('')+'</details></details>'+
 '<p class="route-disclaimer">번호·점선은 방문 순서 연결선이며 실제 도보 경로가 아닙니다. 거리·시간·통제는 길찾기에서 확인하세요. '+(r.taxi?'호텔 짐 회수 이후 Termini는 택시이며 마지막 구간은 차량 길찾기입니다.':'')+'</p>';
 if(points.length>1)L.polyline(points.map(p=>[p.lat,p.lng]),{color:'#bd762e',weight:3,dashArray:'5,8',opacity:.8,interactive:false}).addTo(routeLayer);
 points.forEach((p,i)=>L.marker([p.lat,p.lng],{icon:L.divIcon({className:'',html:'<span class="route-pin">'+(i+1)+'</span>',iconSize:[30,30],iconAnchor:[15,15]}),title:(i+1)+'. '+p.name,zIndexOffset:500}).addTo(routeLayer).on('click',()=>{if(!picking)selectPlace(p.id)}));
 if(fit&&points.length){if(points.length===1)map.setView([points[0].lat,points[0].lng],15);else map.fitBounds(points.map(p=>[p.lat,p.lng]),{padding:[40,45],maxZoom:15});}
 $('#routeDetails').addEventListener('toggle',e=>{routeExpanded=e.target.open});
}
$('#routeWorkspace').addEventListener('change',e=>{
 const fields={routeChoice:v=>routeChoice=v,routeHotel:v=>routeHotel=v,routeDinner:v=>routeDinner=v,routeLunch:v=>routeLunch=v};
 if(!fields[e.target.id])return;fields[e.target.id](e.target.value);courseActive=true;
 try{localStorage.setItem('italia-route-view-v1',JSON.stringify({route:routeChoice,hotel:routeHotel,dinner:routeDinner,lunch:routeLunch}))}catch{}
 renderRoutes(true);setTimeout(()=>map.invalidateSize(),100);
});
function routeClick(e){if(e.target.closest('#courseToggle')){courseActive=!courseActive;renderRoutes(courseActive);return;}const b=e.target.closest('[data-route-place]');if(b)selectPlace(b.dataset.routePlace);const choice=e.target.closest('[data-plan-route]');if(choice){courseActive=true;routeChoice=choice.dataset.planRoute;routeHotel='memphis';if(routeChoice.startsWith('revised-oct4'))routeLunch='emma';routeExpanded=true;renderRoutes(true);$('#routeWorkspace').scrollIntoView({block:'start',behavior:'smooth'});setTimeout(()=>map.invalidateSize(),120)}}
$('#routeWorkspace').addEventListener('click',routeClick);
$('#tripOverview').addEventListener('click',routeClick);
const renderPlaces=render;
function renderRoutes(fit=false){
 renderPlaces();buildRoutes(fit&&courseActive);
 const panel=$('#routeWorkspace'),showCourse=courseActive&&!panel.hidden;
 if(showCourse)markers.clearLayers();else routeLayer.clearLayers();
 if(!panel.hidden)panel.insertAdjacentHTML('beforeend','<button type="button" class="plan-route-button" id="courseToggle" aria-pressed="'+courseActive+'">'+(courseActive?'경로 끄기 · 필터의 장소 핀 복원':'경로 켜기 · 경로의 핀만 표시')+'</button><p class="route-disclaimer">'+(courseActive?'현재 경로의 핀만 표시 중 · 날짜·종류 필터는 장소 목록에 유지됩니다.':'경로 꺼짐 · 현재 날짜·종류 필터에 맞는 장소 핀을 표시합니다.')+'</p>');
}
render=function(){renderRoutes()};render();renderRoutes(true);
